[Hemdi] PageLayout 스타일 수정 (FlexBox 적용, size prop 추가)
Co-Studo/Co-Studo-front pull request #101
Opened 2022-11-30 18:38 UTC by hemudi

close #89
## ✨ 구현 내역
- 화면 가운데 고정
- 기존 flex 스타일 -> FlexBox 컴포넌트로 적용
- background 색 추가
- size type prop 추가

이전에 구현해뒀던 PageLayout 입니다!
FlexBox Merge 되고 올려야지했는데 차일피일 미루다가 너무 늦게 올린 것 같네요. 죄송합니다!
현재 페이지 작업 중이신 분들 중에 적용해보시고 이상이 있으시면 말씀해주세요ㅠ-ㅠ

2022-12-01 12:21 UTC, jindonyy requested changes
수고했습니다 햄디 ^___^

2022-12-01 12:21 UTC, jindonyy commented on src/components/common/PageLayout/index.tsx
> +    padding: '6rem',
이 6rem이 상하좌우 모두 필요한게 맞나요?? 좌우에는 4.5rem, 상은 0, 하는 7rem만 주는게 맞는거 같아요!

2022-12-01 12:21 UTC, jindonyy commented on src/components/common/PageLayout/index.tsx
> +    height: '100%',
height: 100%는 둘 다 필요한 속성인가요??

2022-12-01 12:21 UTC, jindonyy commented on src/components/common/PageLayout/index.tsx
>      >
flexBox 중첩하지 않고 margin: auto로 가운데 설정할 수 있어요~!
그리고 bgColor: white도 수정해주세용
```tsx
  <FlexBox
    as="main"
    sx={{
      flexDirection: 'column',
      bgColor: 'white',
      m: '6rem auto 0',
      ...layoutSize[size],
    }}
    {...restProps}
  >
    {children}
  </FlexBox>
```

2022-12-01 12:54 UTC, mina-gwak requested changes
햄디 고생하셨어요 👍 수정이 필요한 부분이 있어서 change request 남기겠습니다!

2022-12-01 12:54 UTC, mina-gwak commented on src/components/common/PageLayout/index.tsx
> +  sx,
sx를 prop으로 받고 있기는 한데 적용하는 곳이 없는 것 같아요!

2022-12-01 12:54 UTC, mina-gwak commented on src/components/common/PageLayout/index.tsx
> +    padding: '6rem',
이 PageLayout을 적용했을 때 padding 때문에 내부에 있는 탭이 끝까지 이어지지 못하고 중간에 떠있게 되더라구요. 내부의 padding은 스터디 상세 페이지처럼 필요없는 곳도 있으니 없어도 되지 않을까 싶습니다!

padding: 6rem 적용된 상태
<img width="700" alt="스크린샷 2022-12-01 오후 9 43 45" src="https://user-images.githubusercontent.com/62706988/205056944-1f16c1c5-114e-48ed-8d34-6b195055b160.png">

padding: 6rem 제거한 상태
<img width="700" alt="스크린샷 2022-12-01 오후 9 44 25" src="https://user-images.githubusercontent.com/62706988/205057467-f32db9c8-79bc-4657-b785-52b745530dd5.png">

2022-12-01 12:54 UTC, mina-gwak commented on src/components/common/PageLayout/index.tsx
> +      mt: '6rem',
헤더의 길이가 5.875rem이라 mt을 6rem으로 주게 되면 미세하게 공간이 생기더라구요. 헤더와 메인 영역을 구분하는 선처럼 보이긴 해서 크게 거슬리지는 않는데 의도하신 부분인지 궁금했습니다!

2022-12-01 13:17 UTC, mina-gwak commented on src/components/common/PageLayout/index.tsx
> +    height: '100%',
그리고 가장 상위 태그의 height를 기본으로 헤더 영역(5.875rem)을 제외한 나머지를 차지하게 하면 어떨까 싶어요 calc(100vh - 6rem) 이런 식으로요! 지금 페이지의 형태를 보면 컨텐츠가 많지 않더라도 흰색 영역이 페이지 전체를 차지하고 있으니까 기본적으로 그렇게 페이지 레이아웃이 적용되도록 하면 좋을 것 같아요.

+) 추가로 하위 FlexBox에 flex-grow: 1도 적용되면 좋을 것 같네요..!

2022-12-02 03:26 UTC, hemudi commented on src/components/common/PageLayout/index.tsx
>      >
bgColor: 'white' 은 현재 FlexBox 의 bgColor 타입에 맞게 color 의 키값으로 white를 지정한건데 혹시 어떤 값으로 수정해야 할까요??
이 부분은 원래는 나중에 palette에 값이 추가되면 수정하려고 둔 부분이기도 했었습니다.
아예 palette에 Main Background 색으로 white를 추가해서 palette 키 값으로 적용하는게 나을까요?

```tsx
type StyleSX = {
  bgColor?: keyof typeof colors | keyof Palette;
};

const colors = {
   ...
   white: '#ffffff',
}

```

2022-12-02 03:27 UTC, hemudi commented on src/components/common/PageLayout/index.tsx
> +  sx,
으앜 계속 수정하다가 빼먹었네여 감사합니다 ^-ㅠ)b

2022-12-02 04:27 UTC, hemudi commented on src/components/common/PageLayout/index.tsx
> +      mt: '6rem',
넵 현재 헤더에 길이에 맞춰서 제 눈으로 봤을때 6rem이 제일 어색하지 않은 것 같아서 정한 값이었습니다!
Header 에 딱맞추는게 나을까요?

2022-12-02 05:04 UTC, hemudi commented on src/components/common/PageLayout/index.tsx
> +    height: '100%',
오옹 100%라고 하는것보다 좀 더 의미있는 값이 될 것 같네요!
그리고 혹시 하위 Flexbox는 위의 [도니가 남겨주신 의견](https://github.com/Co-Studo/Co-Studo-front/pull/101#discussion_r1037042798)대로 하위 태그는 없애고 marin 에 auto 를 적용해볼까 하는데 어떻게 생각하시나요?

2022-12-02 05:05 UTC, hemudi commented on src/components/common/PageLayout/index.tsx
> +    padding: '6rem',
으음 확실히 padding은 제외하는게 좀 더 자유로운 마크업이 가능할 것 같네요ㅠ 감사합니다!

2022-12-02 05:08 UTC, mina-gwak commented on src/components/common/PageLayout/index.tsx
> +      mt: '6rem',
아니요 괜찮은 것 같아요! 수정을 요청드리는 건 아니고 궁금해서 여쭤봤던 부분이었습니다 ㅎㅎ

2022-12-02 05:09 UTC, mina-gwak commented on src/components/common/PageLayout/index.tsx
> +    height: '100%',
flex grow는 꼭 FlexBox가 아니라도 적용할 수 있으니 괜찮을 것 같습니다 👍

2022-12-02 05:36 UTC, hemudi commented on src/components/common/PageLayout/index.tsx
> +    height: '100%',
<img width="604" alt="스크린샷 2022-12-02 오후 2 27 11" src="https://user-images.githubusercontent.com/34249911/205221297-72c816da-6bd8-4f13-bea3-19bdfba2b5f9.png">
저희 디자인이 컨텐츠가 적어도 세로가 전부 흰 배경으로 채워져서 두 사이즈 다 기본적으로 height 를 100%를 줬습니다!

그리고 size 별로 중복되는 값이어도 따로 정의해놓고 관리하는게 유지보수에 좋을까 싶어서 각각 정의한거긴 한데
문득 생각해보니 결국 width, height 은 최대 넓이로 지정하고 max, min 값으로 실질적인 사이즈를 제어 할테니 굳이 중복을 감수하고 따로 정의 해둘 필요가 있나 싶은 생각이 드네요. @-@)

2022-12-02 05:54 UTC, hemudi commented
## 1차 변경사항
### 1. 가운데 정렬을 위한 중첩 FlexBox 태그 제거
도니의 피드백대로 중첩된 구조로 가운데 정렬을 하는 것보다 maring 값을 사용해 정렬하는게 제일 노멀하고 불필요한 중첩을 제거할 수 있는 방법이라 생각이 들어 반영했습니다.
그래서 하위 FlexBox를 제거하긴 했는데 루트인 main 태그의 Flex 속성은 유지시켜도 괜찮지 않을까 싶어서 상위 FlexBox는 그대로 남겨뒀습니다.

### 2. layoutSize 중복되는 width, height 값 제외
```tsx
const layoutSize = {
  wide: {
    width: '100%',
    height: '100%',
  },
  default: {
    width: '100%',
    height: '100%',
    maxWidth: '1270px',
  },
};
```
사이즈 타입 별 속성값을 저장한 layoutSize 객체에서 중복되던 width, height 값을 제외했습니다.
후에 사이즈 변경이 있을 때 분리하는것보다 각각 정의해두는게 유지보수에 좋지 않을까 싶었는데 생각해보니 사이즈 변경이 있다 하더라도 width, height는 최대 넓이를 가지고 max, min 값으로 제어를 할 것 같아서 제외하고 wide 속성에 max-width의 기본값인 none을 추가하여 default 값과의 차이를 명시해줬습니다!

### 3. Header height 상수화, padding 제거
```tsx
const HEADER_HEIGHT = '6rem';

height: `calc(100vh - ${HEADER_HEIGHT})`,
m: `${HEADER_HEIGHT} auto 0`,
```
기존 margin의 top 값으로 header 의 높이를 고려하여 6rem 값을 적용했었는데 해당 값의 의미를 상수화 시켜 명확히 하는게 좋을 것 같아서 분리했습니다. 또한 제이미의 피드백대로 height 에도 적용하고 추가로 padding 값도 제거했습니다!

### 4. PageLayoutSX 제거
기존에 pageLayout의 width, height, backgroundColor 를 커스텀 할 수 있던 SX 속성이 불필요하다 생각하여 제거하였습니다.
PageLayout 을 적용하는 이유가 균일한 규격을 위해서 라고 생각해서 SX 가 아닌 size 속성을 이용해 일관되게 사이즈 변경이나 속성을 변경하는게 좋을 것 같습니다.

@jindonyy @mina-gwak @healtheloper  2차 PR 리뷰 부탁드립니다! （ʃƪ＾3＾）

2022-12-02 06:04 UTC, mina-gwak approved these changes
LGTM 👍

2022-12-02 06:20 UTC, healtheloper commented on src/components/common/PageLayout/index.tsx
>      >
일단 팔레트가 다크모드를 고려하긴 했으니 추후 white 라는 이름보다는 bgColor 와 관련된 이름으로 수정되면 될 것같아요

2022-12-02 06:22 UTC, healtheloper reviewed
도니가 changed request 남기셨긴 하셔서 일단 Comment 로 남길게요~
LGTM

2022-12-05 13:29 UTC, jindonyy commented on src/components/common/PageLayout/index.tsx
>      >
colors꺼를 불러오지 않고 white로 해서 말했던건데 어차피 지금 palette가 수정됐으니 머지되면 제가 팔레트로 수정할께용!

2022-12-05 13:33 UTC, jindonyy commented on src/components/common/PageLayout/index.tsx
> +    padding: '6rem',
저도 이 부분을 봤었는데요ㅠ 여기 부분을 제외한 페이지는 양옆 padding이 필요한데  저 부분 때문에 빼야하는거니.. 디자인을 수정 요청하던지 wide처럼 padding을 true, false 해주는게 낫겠다고 생각했어요. 근데 디자인을 살리는 방향으로 해서 padding을 prop으로 끄고 킬수있는게 좋을거 같아요!

2022-12-05 13:34 UTC, jindonyy commented on src/components/common/PageLayout/index.tsx
> +      mt: '6rem',
딱 맞추는게 당연히 좋을거 같아요! 근데 header는 고정 높이로 들어가야하는게 맞으니 header를 6rem으로 변경하는게 나을듯하네요~

2022-12-05 13:34 UTC, hemudi commented on src/components/common/PageLayout/index.tsx
>      >
아하! 그 부분은 FlexBox 내부에 있습니당!
FlexBox의 bgColor 값으로 color의 key 나 Palette 의 key 값을 넘겨주면 FlexBox 내부에서 colors나 palette에서 불러오고 있어요!

```tsx
// FlexBox
const getFlexCssProperties = (sx: FlexBoxSX, theme: DefaultTheme) =>
  Object.entries(sx).reduce((css, [key, value]) => {
    switch (true) {
      case key === 'bgColor':
        return {
          ...css,
          backgroundColor: theme.palette[value] ?? colors[value],
        };
...
}
```

2022-12-05 13:35 UTC, jindonyy commented on src/components/common/PageLayout/index.tsx
> +    height: '100%',
calc(100vh - 6rem)로 지정하려면 min-height로 지정해야할거 같아요~

2022-12-05 13:41 UTC, hemudi commented on src/components/common/PageLayout/index.tsx
> +    padding: '6rem',
흠 옵션으로 선택할 수 있게 하는 것도 괜찮을 것 같네요
그런데 혹시 padding 만을 위한 prop을 하나 새로 추가하는 것보다 size의 타입을 하나 더 추가하는 방법은 어떠신가요?
가능하면 prop을 안늘리고 싶고 사용하는 곳에서도 간단하게 size prop 으로만 설정하도록 하는게 편할 것 같아서요!

```tsx
type PageLayoutProps = {
  children: ReactNode;
  size?: 'wide' | 'default' | '하나 더';
  sx?: PageLayoutSX;
};
```

2022-12-05 13:45 UTC, hemudi commented on src/components/common/PageLayout/index.tsx
> +    height: '100%',
혹시 min-height 으로 지정해야 하는 이유를 여쭤봐도 괜찮을까요? ^//^)>

2022-12-07 02:26 UTC, closed without merging