[Jamie] 스터디 상세 페이지 공통 레이아웃
Co-Studo/Co-Studo-front pull request #105
Opened 2022-12-08 10:01 UTC by mina-gwak

close #99 

스터디 상세 페이지에서 공통으로 사용할 레이아웃을 작성했습니다.

- 파크가 보내주시는 스터디 정보와 StudyEntity가 일부 다른 부분이 있어서 수정
- 현재 url에 따라 활성화된 탭을 변경하도록 하려면 cos-ui에서 수정이 필요해서 추가로 수정할 계획

2022-12-08 15:48 UTC, jindonyy requested changes
tab 구현한 부분이 좋네요!! naviagte, useLayoutEffect 👍
몇 개 빠진 부분이 있어서 request change로 남겨요!
수고했어용 쨈 >_<

2022-12-08 15:48 UTC, jindonyy commented on src/pages/StudyDetailPage/index.tsx
> +  if (isLoading || !data) return <LoadingSpinner />;
data가 없을 때는 에러처리 해야하지 않을까요??

2022-12-08 15:48 UTC, jindonyy commented on src/pages/StudyDetailPage/index.tsx
> +        height: 100vh;
`min-height: calc(100vh - 6rem)`이 맞을거 같아용

2022-12-08 15:48 UTC, jindonyy commented on src/pages/StudyDetailPage/index.tsx
> +            width="142px"
css prop으로 width: 14.2rem 이 맞는거 같아용
지금은 html에 width로 주고있어보여여

2022-12-08 15:48 UTC, jindonyy commented on src/pages/StudyDetailPage/index.tsx
> +                as="h3"
h태그보다는 dt 태그가 더 어울리지 않나 싶어여 FlexBox가 dl이구!

2022-12-08 15:48 UTC, jindonyy commented on src/pages/StudyDetailPage/index.tsx
> +                </AvatarGroup>
+3 more 글자 관련 부분은 빠진거 같아요~!

2022-12-08 15:48 UTC, jindonyy commented on src/pages/StudyDetailPage/index.tsx
> +            color={isMember ? 'neutral' : 'primary'}
color가 primary일 때 disabled가 true이면 bgColorrk primary_light로 변하긴 해요! 확실히 disabled로 보이고 싶으면 지금처럼 nuetral로 해도 될거 같네용

2022-12-08 15:48 UTC, jindonyy commented on src/pages/StudyDetailPage/index.tsx
> +            {!isAdmin && !isMember && '스터디 가입 신청'}
isMember에 관리자도 포함이 되나요?? 된다면 !isMember만 체크하면 될거 같고, 포함이 안된다면 관리자일 때 버튼이 disabled 될거 같아요!

2022-12-08 16:09 UTC, mina-gwak commented on src/pages/StudyDetailPage/index.tsx
> +  if (isLoading || !data) return <LoadingSpinner />;
data는 디스트럭처링 때문에 넣은 거긴 한데 if (isError || !data) 이런 식으로 따로 빼서 에러처리해주는 게 더 나을 것 같긴 하네요! 에러 처리하는 부분은 이 페이지뿐만 아니라 전체적으로 필요한 부분인 것 같아서 어떤 식으로 처리할지 논의 후 수정해도 좋을 것 같아요.

2022-12-08 16:10 UTC, mina-gwak commented on src/pages/StudyDetailPage/index.tsx
> +        height: 100vh;
여기서는 PageLayout을 안 쓰고 있어서 100vh를 쓰지 않고 작성해주신 대로 하면 아래에 6rem만큼 빈 공간이 남게 돼요! PageLayout이 수정되면 추가로 반영할 계획이라 아직은 괜찮을 것 같습니당

2022-12-08 16:14 UTC, mina-gwak commented on src/pages/StudyDetailPage/index.tsx
> +                </AvatarGroup>
이 부분은 AvatarGroup에서

2022-12-08 16:20 UTC, mina-gwak commented on src/pages/StudyDetailPage/index.tsx
> +            color={isMember ? 'neutral' : 'primary'}
이 부분은 디자인 기준으로 표현한 거긴 해요! 저는 개인적으로 회색이 좀 더 확실하게 보여서 이렇게 유지해도 되지 않을까 싶습니당..! 일반 버튼의 disabled는 폼에서 입력해야하는 값을 모두 입력하지 않았을 경우처럼 원래 가능한데 특정 조건때문에 잠시 불가능해진 경우를 표현할 때 쓰면 좋지 않을까 싶어요!

2022-12-08 16:23 UTC, mina-gwak commented on src/pages/StudyDetailPage/index.tsx
> +            {!isAdmin && !isMember && '스터디 가입 신청'}
저는 포함이 안되는 것으로 이해했습니다! 스웨거에 있는 스터디 정보 api에 요청했을 때를 확인해보면 owner는 지정되어 있고 participants는 빈 배열로 두셨더라구요. 포함된다면 owner에 있는 사람 정보를 participants에 포함해서 보내주셨을 것 같은데 그러지 않아서 포함이 안되는가보다 했어요! 

> 포함이 안된다면 관리자일 때 버튼이 disabled 될거 같아요!

이 부분 잘 이해가 안되는데 좀 더 설명해주실 수 있을까요??

2022-12-08 16:27 UTC, jindonyy commented on src/pages/StudyDetailPage/index.tsx
> +                </AvatarGroup>
앗 저렇게 들어가있는거군영 넵 🫡

2022-12-08 16:28 UTC, jindonyy commented on src/pages/StudyDetailPage/index.tsx
> +            color={isMember ? 'neutral' : 'primary'}
음.. 근데 디자인이 좀 애매하네여 체크아웃이랑 스터디 생성은 neutral 이 활성화된 버튼으로 쓰이고 있어서 ^_ㅠ
그럼 디자인대로 진행해주세요~~

2022-12-08 16:29 UTC, jindonyy commented on src/pages/StudyDetailPage/index.tsx
> +            {!isAdmin && !isMember && '스터디 가입 신청'}
아하 헷갈렸네영 포함이 안되있다면 지금이 맞는거 같아요 ㅎㅎ

2022-12-12 02:32 UTC, healtheloper commented on src/pages/StudyDetailPage/index.tsx
> +            {!isAdmin && !isMember && '스터디 가입 신청'}
>  owner는 지정되어 있고 participants는 빈 배열로 두셨더라구요.

이건 맨 처음 메인페이지에서 owner 와 participants 구분을 위해서만을 생각했었는데 추후 owner 도 participants 안에 포함되는게 편할 수 있다면 변경될 여지가 있겠네요

2022-12-12 03:11 UTC, healtheloper approved these changes
데이터구조 때문에 고생하셨을 것 같네요 (죄송 ㅠㅠ)
주말에 [이 영상](https://youtu.be/edWbHp_k_9Y)을 다시 한 번 봤었는데, Page 에서 JSX 를 만들 때 어느정도로 추상화 해야할지?
추상화 단계에 대한 고민이 생겼습니다. ( 이때문에 Row 컴포넌트를 통해 단계를 맞춰줘도 좋을 것 같다고 생각했어요 )

고생하셨어요~

2022-12-12 03:11 UTC, healtheloper commented on src/apis/user.ts
>  };
이건 아마 firebase 에서 내려주는 데이터구조 보시고 고치신거겠죠?? 👍

2022-12-12 03:11 UTC, healtheloper commented on src/pages/StudyDetailPage/TabBar.tsx
> +const TabBar = () => {
TabBar 가 해당 Page 의 성격만 있는 것 같진 않아서 components 폴더에 두는건 어떠신가요?

2022-12-12 03:11 UTC, healtheloper commented on src/mocks/handlers/studyHandlers.ts
> +  rest.get('/study/id', getStudyDetail),
/study/:studyId 로 해야 params 로 받아올 수 있을 것 같아요~

2022-12-12 03:11 UTC, healtheloper commented on src/pages/StudyDetailPage/index.tsx
> +                <dd>
제가 dl-dt-dd 태그에 대해서 잘 모르는데,
[이 글](https://aoa.gitbook.io/skymimo/aoa-2019/tips-2/dl-dt-dd-.)만 봤을 때에는 dl-dt-dd 가 하나로 묶여 사용되는 것 같아서
textAlign 하고있는 div 가 dl 이 되어야 할 것 같다고 생각했어요, 지금은 FlexBox (dl) 이 두 쌍을 가지고 있어서요

dl-dt-dd 의 사용 목적이 시멘틱을 위한 것인지? 궁금해지네요, 이점이 있고 사용해야 한다면 현 구조는 복잡해보여서 이를 추상화한 컴포넌트가 필요하다고 느껴졌어요

2022-12-12 07:59 UTC, mina-gwak commented on src/pages/StudyDetailPage/TabBar.tsx
> +const TabBar = () => {
페이지 전체에서 저 탭은 상세 페이지에서 한번만 사용되긴 해요! 레이아웃의 헤더에서는 관련된 UserInfoCircle이 같이 있길래 비슷한 느낌으로 같이 두긴 했는데 혹시 해당 페이지의 성격만 있는 것 같지 않다는 게 어떤 의미일까요? 여러 곳에서 사용될 수 있다는 느낌으로 말씀하신 걸까요??

2022-12-12 08:04 UTC, mina-gwak commented on src/pages/StudyDetailPage/index.tsx
> +                <dd>
저는 시맨틱한 마크업을 위한 거라고 생각했습니다!
구조 같은 경우는 저런 식으로 사용될 수 있는 것 같아요. [이 글](https://www.stefanjudis.com/today-i-learned/divs-are-valid-elements-inside-of-a-definition-list/)에 있는 W3C 권장사항을 보시면 example에서 저와 비슷하게 사용한 예시를 확인하실 수 있습니다! 저는 개인적으로 이런 구조도 기본적인 마크업 수준인 것 같아서 크게 복잡하다고 느껴지진 않는 것 같아요!

2022-12-12 08:12 UTC, healtheloper commented on src/pages/StudyDetailPage/TabBar.tsx
> +const TabBar = () => {
> 여러 곳에서 사용될 수 있다는 느낌으로 말씀하신 걸까요??

네네 굳이 StudyDetailPage 폴더 하단에 있어야 할까 싶어서요
현재 디자인 상으로는 상세페이지에서만 쓰이더라도 향후 다른 곳에서도 쓰일 수 있겠다는 생각입니다
(~~아주 먼 옛날 만들었던..~~ UserInfoCircle 요놈도 옮기는게 맞는 것 같습니다)

2022-12-12 08:38 UTC, healtheloper commented on src/pages/StudyDetailPage/index.tsx
> +                <dd>
제이미가 사용하신 것 처럼 사용할 수는 있지만 스크린리더가 제대로 읽는데 문제가 있다는데, 어떤 문제인지 직접 확인해 봐야 따져볼 수 있겠네요, 구조에 대한건 추상화 단계를 좀 높일지 말지에 대해서 같이 의논해봐도 좋을 것 같아요

2022-12-12 12:03 UTC, jindonyy approved these changes
수고하셨습니당 ^_^)b

2022-12-12 12:03 UTC, jindonyy commented on src/pages/StudyDetailPage/index.tsx
> +                <dd>
dl 하위에 div가 들어갈수 있는건 처음 알았네여.. 언제 바뀌었담^_ㅠ.. 저도 저 구조면 리더기에서 제대로 읽을수 있는가 하는 생각이 들긴했네여. 그래도 웹표준에 어긋나는건 아니니 현재는 괜찮다고 생각해여!

2022-12-12 12:03 UTC, jindonyy commented on src/pages/StudyDetailPage/index.tsx
> +                <dd>
dl 하위에 div가 들어갈수 있는건 처음 알았네여.. 언제 바뀌었담^_ㅠ.. 저도 저 구조면 리더기에서 제대로 읽을수 있는가 하는 생각이 들긴했네여. 그래도 웹표준에 어긋나는건 아니니 현재는 괜찮다고 생각해여!

2022-12-12 13:13 UTC, merged