[Hemdi] Radio Component 생성
Co-Studo/Co-Studo-front pull request #24
Opened 2022-09-27 08:17 UTC by hemudi

issue #19 

![RadioGroup exam](https://user-images.githubusercontent.com/34249911/192448218-011560ba-288a-46d8-aee6-3b420b2819a3.PNG)
[↳ CodeSandBox에서 실행해보기](https://codesandbox.io/s/headless-radiogroup-nml52g?file=/src/App.js)

## 🤔 구현하면서 고민한 사항

<details>
<summary><h3>1. Headless 설계<h3></summary>

![스크린샷 2022-09-23 오전 8 48 29](https://user-images.githubusercontent.com/34249911/192456944-3b8b90fa-c1c5-452d-bdc5-8f5f0e51db29.png)
#### RadioGroup 컴포넌트는 무엇을 하는 컴포넌트인가?
- 그룹을 대표하는 **Title**을 가지고 있다.
- 그룹으로 묶인 **라디오 버튼(Option)** 들을 가지고 있다.
    - 각 버튼들은 **어떤 옵션인지에 대한 설명(label)** 을 가지고 있다.
- 상태값으로 **선택된 옵션**이라는 값을 다룬다.

#### 컴포넌트 사용자가 할 수 있는 기능은?
- Title을 원하는 위치에 추가하여 수정하거나 제거 할 수 있다.
- Option을 추가할 수 있다.
- Option의 label을 사용자가 자유롭게 추가 할 수 있게 구현.
- Option 선택 시의 이벤트(onChange) 를 추가할 수 있고, 해당 이벤트 핸들러를 통해 선택된 옵션을 가져올 수 있음.

#### UI 사용자가 할 수 있는 기능은?
- UI 사용자는 마우스로 라디오 버튼 그룹의 옵션들 중 하나를 선택할 수 있다.

</details>
<details>
<summary><h3>2. Optional Id</h3></summary>

```tsx
const Option: React.FC<RadioOptionProps> = ({ id , ...props}) => {
  const { name, selectedValue, onChange } = useRadioContext();
  const optionId = id || `option-${name}-${value}`;  // 요기
  return (
    <div {...props}>
      <input
        type="radio"
        name={name}
        id={optionId}
        ...
      />
      <label htmlFor={optionId}>{children}</label>
    </div>
  );
};
```
Input 과 Label 을 연결하기 위해서는 동일한 id를 반드시 설정해줘야 함.
하지만 각 Option 별로 고유한 value 값도 설정을 하고 있는데 굳이 id를 또 따로 사용자가 입력해주는 건 코드도 복잡해지는 것 같고 번거로운 것 같다고 느낌.
어차피 submit 시에도 name 값이 쓰이니 옵션 별 id의 용도가 단순히 Input 과 Label을 연결하기 위함이라면 어떤 값이든 상관없을 것 같아 Optional로 설정하고 undefined인 경우 임의로 생성(`option-${name}-${value}`)해주는 식으로 구현함.

</details>

## 📢PR을 통해 논의하고 싶은 것!!!
### Headless 컴포넌트의 하위 컴포넌트 타입 지정 방식
[[ESLint / TypeScript] Optionl 속성의 default value 문제 + React.FC 사용 논의](https://github.com/Co-Studo/Co-Studo-front/discussions/22)

위의 Discussion 을 통해 최종적으로 컴포넌트들의 타입을 React.FC으로 지정하기로 결정한 뒤 적용을 해보니 Headless 컴포넌트에 하위 컴포넌트를 추가하는 부분에서 type 에러가 발생했습니다.

![image](https://user-images.githubusercontent.com/34249911/192461689-3d0cfe16-038e-4a02-ab8b-3ffffb237fcc.png)
![error](https://user-images.githubusercontent.com/34249911/192461606-7b43d34a-a579-4be6-80a4-a4c7c1b072e3.PNG)

```tsx
type RadioGroupChildren = {
  Title: React.FC<TitleProps>;
  Option: React.FC<OptionProps>;
};

const RadioGroup: React.FC<RadioGroupProps> & RadioGroupChildren = ({}) => {}
```

그래서 위와 같이 하위 컴포넌트의 타입을 따로 정의해서 추가해줘서 [오류는 해결](https://github.com/Co-Studo/Co-Studo-front/commit/11566fae5e0db91300f279fd2b0f2e670e94707a#diff-21e61eb3de84152155a0f307cfe48463ad89adf2b1a647b7cfb1d59ad469819eR33)은 했는데 **적절한 네이밍**인지,
이게 최선의 해결 방법인지 의문이 들었습니다.
그리고 모든 Headless 컴포넌트에서 방식이나 네이밍을 통일 하는게 좋을 것 같아서 함께 의논을 해보고 싶습니다!

제가 위 방식이 최선의 해결 방법인지 의문이 든 포인트는 하위 컴포넌트는 추가되거나 변경, 삭제 될 수 있는 요소인데 그럴 때마다 계속 type을 수정해줘야 한다는 점 + `React.FC<RadioGroupProps> & RadioGroupChildren` 이 부분의 가독성이 그렇게 좋아보이지 않다는 점입니다.

그래서 다른 방법이 없을까 싶어서 찾아보니 [stackoverflow ](https://stackoverflow.com/a/60021394)에서 아래와 같은 방법도 있더라구요.

```tsx
const RadioGroupComponent: React.FC<RadioGroupProps> = ({}) => {}
const Option: React.FC<RadioOptionProps> = ({}) => {}
const Title: React.FC<TitleProps> = ({ children, ...props }) => ({}) => {}

const RadioGroup = Object.assign(RadioGroupComponent, { Option, Title });
export default RadioGroup;
```

type을 지정해주지 않고 Object.assign을 이용해 객체를 합쳐 export 하는 방식입니다. 
괜찮아 보이긴 한데 만약 이 방식을 적용해야 한다면 현재의 모든 Headless 컴포넌트에서 방식을 다 통일하는 작업을 해야해서
그냥 type 변동으로 인한 코드 수정을 감수하고 현재의 방식으로 하는 게 나은 것 같기도 합니다. @ _@)

2022-09-27 09:30 UTC, healtheloper requested changes
고생하셨습니다 햄디!

같이 이야기해보고싶은 부분이 꽤 있어서 Request changes 로 드릴게요!

개인적으로 selected value 관련해서는 RadioGroup 에서 관리해야하지 않을까 란 생각을 막연히 갖고 있었는 데 Form 의 validation 을 쉽게 다루기 위해서는 RadioGroup 을 사용하는 곳 에서 상태를 선언하고 주입해주는 방식이 더 낫겠다는 생각이 들었어요! 이 부분이 좋았습니다 👍👍

2022-09-27 09:30 UTC, healtheloper commented on src/components/common/RadioGroup/index.tsx
> +};
저는 React 에서 EventType 을 SyntheticEvent 로 사용하는 편인데요, 
FormEvent 는 어떤 의도의 타입으로 사용되는 건가요? 
저는 단순히 Form 이벤트 일 때 사용해야하나? 라고 막연히 생각만 했어서 질문드립니다

2022-09-27 09:30 UTC, healtheloper commented on src/components/common/RadioGroup/index.tsx
> +  }
이건 개인 취향일 수 있는데 
undefined 를 값으로 취급하는 것에 대한 불안함? 같은 것 때문에 저는 개인적으로 context 가 없을 때 라고 명시하는 편 이거든요, 이거는 다른분들은 어떻게 생각하시나요?

```tsx
 if (!context) {
    throw new Error('useMyContext should be used within MyContext.Provider');
  }
```

2022-09-27 09:30 UTC, healtheloper commented on src/components/common/RadioGroup/index.tsx
> +};
type 과 interface 에 관해 한번 정리하고 넘어갈 필요가 있을 것 같은데,
저는 개인적으로 상속을 쓸 때에는 interface 가 자연스럽다고 생각이 드는 편 이라

상속으로 확장하는 것 -> interface
그 외 -> type

으로 사용하는 편인데 다른 분들은 어떠신가요?

+)
만약 children 만 포함되는 거라면 `PropsWithChildren<RadioState>` 로 사용해도 됩니다!

2022-09-27 09:30 UTC, healtheloper commented on src/components/common/RadioGroup/index.tsx
> +};
개인적으로 useMemo 는 Profiler 로 잡아낸 이후에 쓰는 것을 선호하는데요,
이유는 불필요한 최적화일 수도 있기 때문이에요, 
어차피 매 dispatch 마다 바뀌는 상태면 memoization 을 굳이 할 필요가 없으니 오히려 메모리 낭비일 수 있어요.

그래서 values 에서 덜어낼 게 없을까? 를 생각해보았을 때
**name, onChange 가 꼭 context value 로 필요할까?** 라는 생각이 먼저 들었어요.

children 을 map 으로 돌면서 각 children 에 name, onChange 를 넘겨주는 방법을 생각했는데
Title 도 children 으로 포함되는 문제가 있네요.

여기서 두번째 생각이 들었어요. Title 이 RadioGroup 의 Compound Component 로 꼭 필요할까?
내가 Radio Group 을 쓴다고 생각해 보았을 때 Title 은 필수요소가 아니라는 생각이 들었어요.

2022-09-27 09:30 UTC, healtheloper commented on src/components/common/RadioGroup/radioGroup.styled.tsx
> +};
뭔가 Title 을 덜어내면 OptionWrapper 라는 애도 덜어내고 
Group 에 props 를 통해서 스타일을 변동할 수 있을 것 같아요

2022-09-27 10:27 UTC, hemudi commented
> +) 리뷰 달고나니 issue 가 close 되어 있는데 PR merge 되면 자동으로 닫히지 않나요?!

헉 수동으로 닫아줘야 하는 건 줄 알았어요!
다시 reopen 했습니다...^//^)>

2022-09-27 10:53 UTC, hemudi commented on src/components/common/RadioGroup/index.tsx
> +};
FormEvent는 [Forms and Events](https://react-typescript-cheatsheet.netlify.app/docs/basic/getting-started/forms_and_events/) 이 글을 참고해서 사용하기 시작한 타입입니다!
해당 글을 보면 Form 또는 Form 요소(input) 의 focus, change, submit 이벤트 시 사용하는 것 같네요!

저는 EventType을 가능하면 어떤 이벤트인지 명확히 나타내는 타입을 쓰는 것이 가독성이 더 좋지 않을까 싶고 상속 받아 해당 이벤트에 맞게 속성들이 추가되기도 하는 것 같아서 SyntheticEvent 보다는 SyntheticEvent 를 상속 받은 Event 타입들을 찾아 쓰는 편인 것 같아요!
결국 내부적으로는 SyntheticEvent 를 상속 받은 타입들이니까 추가 커스텀이나 확장이 필요하지 않는 이상 명확한 타입을 정의해주는게 좋지 않을까 싶어서요!

그런데 파크의 질문을 보고 이래저래 생각해보니
Headless 컴포넌트 같이 확장성을 고려해야 하는 경우라면 특정 타입을 정해놓는 것보단 SyntheticEvent 를 쓰는게 확장성이 더 좋은걸까 싶은 생각도 드네요. @_@)>

2022-09-27 10:57 UTC, hemudi commented on src/components/common/RadioGroup/index.tsx
> +};
+) FormEvent 검색해보다 찾았는데 onChange는 React.ChangeEvent<HTMLInputElement> 라는 타입으로 지정해주는 것이 좀 더 정확하다고 하네요....([stackoverflow](https://stackoverflow.com/a/42085792))

2022-09-27 11:11 UTC, hemudi commented on src/components/common/RadioGroup/index.tsx
> +};
앗 이 부분은 첫 주차 때 [파크가 내주신 의견대로 정했던 부분](https://costudo.notion.site/348ac17462d1497fb36d8ea5eb645886#4faa52ad8703435592ce136fb75690ba)인데 제가 제대로 숙지를 못한 부분인 것 같네요! ㅠ_ㅠ)
Notion 의 코딩 컨벤션 문서에도 추가 해놓겠습니다!

저는 해당 방식에 이견이 없습니다!
다른 분들도 이견이 없으시면 수정하도록 하겠습니다!! ^^)7

+) PropsWithChildren ^0^)b 짱!

2022-09-27 11:20 UTC, hemudi commented on src/components/common/RadioGroup/index.tsx
> +  }
저도 개인적으로 undefined 값은 개발자가 컨트롤 할 수 없는 비어있는 값이고
null 이 개발자가 컨트롤 가능한 빈 값이라고 생각해서 코드 상에 직접 undefined 를 쓰는건 별로 좋아하지 않는데
지난 [PR에서 같이 얘기했던 코드](https://github.com/Co-Studo/Co-Studo-front/pull/13#discussion_r975756209)라 제가 변경해도 괜찮나 싶어서 그냥 뒀었어요ㅎㅎ!
다들 동의하시면 if(!context) 로 수정하는게 좋을 것 같습니다! ^0^)b

2022-09-27 14:26 UTC, healtheloper commented on src/components/common/RadioGroup/index.tsx
> +};
오홍 범용적인걸 고려하더라도 어쨋건 onChange 이벤트에만 사용되는 거니 ChangeEvent 가 적절하다고 생각됩니다~~

2022-09-29 02:34 UTC, jindonyy approved these changes
저도 상태가 주입되는 부분이 좋네요 ^0^)b
고생했어요 햄디~~!

2022-09-29 02:34 UTC, jindonyy commented on src/components/common/RadioGroup/index.tsx
> +  ...props
그.. 되게 사소한건데.. 저는 prop 선언할 때 해당 컴포넌트가 가지는 특수한 prop은 위에 적고  그 다음으로 다른 컴포넌트들도 가질 수 있는 event, children 순으로 적는데요. prop을 통해서도 해당 컴포넌트의 기능을 추론할 수 있다고 생각해서 이 순으로 적으려고(저도 가끔 까먹기도 하지만ㅋㅋ) 하는데 어떻게 생각하시나요??

2022-09-29 02:34 UTC, jindonyy commented on src/components/common/RadioGroup/index.tsx
> +      <label htmlFor={optionId}>{children}</label>
radio 버튼의 기본 디자인을 그대로 쓰지 않는 경우가 많자나요. 그래서 스타일을 이후에 입혀줘야할텐데 지금은 radio랑 label이 묶여서 하나의 컴포넌트라 스타일을 못입히지 않나라는 생각이 드네요. 둘을 분리해야되지 않을까용??

2022-09-29 02:40 UTC, jindonyy commented on src/components/common/RadioGroup/index.tsx
> +};
아마 useMemo를 쓰라고 eslint에서 경고해서 쓰지 않았을까..하고 조심스레 추측해봅니다ㅎㅎ 근데 파크 말대로 지금 상황에서 재렌더되는 경우는 selectValue가 바뀌었을 때 뿐인거 같아서 values가 계속 바뀌기 때문에 메모이제이션을 안해도 되지 않을까 싶네요! 해당 옵션을 끌까요..?

그리고 Title은 radio 버튼의 기능을 생각하면 필수가 아닌거 같아요. UX적으로는 radio버튼만 있고 어떤거에 대한 radio인지 안적혀있을 수가 있나라고 생각해서 필수라고 생각하는데요. 그런데 지금은 headless 컴포넌트를 만드는거니 radio의 기능 관점에서는 필요없는게 맞다고 생각합니다.

2022-09-29 02:42 UTC, jindonyy commented on src/components/common/RadioGroup/index.tsx
> +};
이전에는 대부분 interface를 쓰고 객체가 아닌 타입 지정할 때만 type을 썼었어요.
```ts
type Size = 'large' | 'small';

type Status = 'open' | 'closed';

interface ILabelProps {
  children: React.ReactNode | string;
  size?: Size;
  status: Status;
  background: string;
}
```
interface가 확장에 더 유연하다고 생각해서 이렇게 써왔었는데요.

다시 공부해보니 type은 선언적 확장이 안되고 interface는 가능하다는 점 때문에 저는 type을 쓰는게 더 안전한거 같네요!
그리고 확장도 [typescript의 wiki](https://github.com/microsoft/TypeScript/wiki/Performance#preferring-interfaces-over-intersections)에
> Type relationships between interfaces are also cached, as opposed to intersection types as a whole. A final noteworthy difference is that when checking against a target intersection type, every constituent is checked before checking against the "effective"/"flattened" type.
-> interface 들을 합성할 경우 이는 캐시가 되지만, 타입의 경우에는 그렇지 못하다.
타입 합성의 경우, 합성에 자체에 대한 유효성을 판단하기 전에, 모든 구성요소에 대한 타입을 체크한다.

라고 적혀있어 type 확장은 컴파일 시에 상대적으로 성능이 좋지 않은 거 같아 확장 때는 interface를 사용하는게 좋은거 같아요!

2022-09-29 02:43 UTC, jindonyy commented on src/components/common/RadioGroup/index.tsx
> +  }
보자마자 든 생각은 context에 null이 들어올 경우가 있나? 였어요.
상상은 안가지만 개발자가 의도하고 context를 사용하지 않기 위해서 value를 null로 지정하는 경우가 아닐까..싶네요. 의도적으로 null로 지정했다면 사용하지 않겠다는 의도인건데 console.error도 아니고 throw error를 하면서 막을 필요가 있나? 싶기도 하네요.
결론은 throw Error를 넣은건 실수로 provider나 value를 지정하지 않을 떄를 대비하기 위한거니 undefined가 적절하지 않나 싶습니다!
(저도 코드상으로 undefined를 좋아하진 않아요 허허)

2022-09-29 03:02 UTC, hemudi commented on src/components/common/RadioGroup/index.tsx
> +  ...props
저는 개인적으로 글자 수에 맞춰서 정리하는게 코드가 깔끔하게 보여 좋아하는 편이었는데^//^)>
확실히 프로젝트 전반적으로 prop 관련 순서를 정해둔다면 다른 분의 코드를 볼 때 기능을 좀 더 쉽게 추론 할 수 있을 것 같네요.
(다만 그렇게 한다면 제 기준에서는 코드를 좀 더 깔끔하게 만들기 위해 prop 네이밍에 고민하는 시간이 좀 더 생길 것 같네요ㅎㅎ)
이것도 일종의 코딩 컨벤션의 영역인 것 같으니 순서를 정할지, 정하면 어떤 순서로 할지 등을 디스커션으로 논의해봐도 좋을 것 같아요!

2022-09-29 04:03 UTC, healtheloper commented on src/components/common/RadioGroup/index.tsx
> +  ...props
저도 비슷한 생각으로 

상단 -> 컴포넌트의 특수한 prop
그 아래 -> native (onChange, children...)
묶어서 쓴다면 -> restProps 와 같은 명시적 이름

으로 의견 냅니다~

2022-09-29 04:09 UTC, healtheloper commented on src/components/common/RadioGroup/index.tsx
> +      <label htmlFor={optionId}>{children}</label>
@jindonyy RadioGroup 아래 Option 이 list item 으로 있는게 인터페이스 적으로 합당하다고 생각되어서 적당한 추상화라고 생각은 드는데 스타일을 입히는게 문제일 수 있겠네요,

버튼에 대한 스타일은 충분히 바꾸고 싶어할 수 있는데, label 에 대한것도 해당될까요?
만약 그렇다면 buttonProps, labelProps 로 넘겨주는 방식도 있을 것 같아요.

2022-09-29 04:43 UTC, healtheloper commented on src/components/common/RadioGroup/index.tsx
> +  }
다시 봤는데 context 가 useContext 의 반환값이라서
초기에 설정한 XXXContext 의 초기값이 무엇이냐에 따라 context 의 값이 달라져요,

저희 코드가 createContext 에 null 을 허용하지 않는 것으로 되어있어서 context 의 초깃값은 무조건 defaultValues 로 되어 있기 때문에 Provder 로 감싸지 않아도 defaultValue 로 셋팅 됩니다.

null 을 허용하는 방향으로 해서 null 여부를 확인할 지 (Provder 로 감싸지 않았는지), 아니면 다른 방법을 찾아봐야할 지 봐야겠어요

[예시로 작성해본 코드](https://codesandbox.io/s/stoic-ully-xshmnx?file=/src/App.tsx) 는 TodoProvder 로 감싸지 않았음에도 오류가 나지 않고 defaultValue 로 셋팅됩니다.

@hemudi @jindonyy @mina-gwak

2022-09-29 08:35 UTC, mina-gwak approved these changes
늦은 리뷰 죄송합니다 🥲
다른 분들이 먼저 잘 말씀해주셔서 관련해서 의견을 조금 얹는 정도로 리뷰를 마칠게요!
고생 많으셨어요 햄디~!!

2022-09-29 08:35 UTC, mina-gwak commented on src/components/common/RadioGroup/index.tsx
> +  }
파크 말씀대로 기본값을 넣어주면 훅에서 context를 체크하는 게 의미가 없어지겠네요.
저는 null을 허용하는 것도 괜찮을 것 같아요! 기본값을 세팅해주는 것보단 null을 허용해서 Provider를 감싸지 않았는지 여부를 확인해 의도하지 않은 대로 동작할 가능성을 없애는 게 더 좋지 않을까 싶습니다.

+) 그리고 에러 메시지에 이전 글에서 넣었던 문구가 그대로 들어가있어요! context 이름을 햄디가 작성하신 context 이름으로 변경해주면 될 것 같네요!

2022-09-29 08:35 UTC, mina-gwak commented on src/components/common/RadioGroup/index.tsx
> +});
context를 생성할 때 displayName을 함께 지정해주도록 하는 건 어떨까요?
지정하지 않았을 때는 Components 탭에서 확인했을 때 그냥 `Context.Provider`라고 보여지는데 displayName을 지정해주면 아래 사진처럼 어떤 컨텍스트의 Provider인지 명시적으로 보여서 이후 여러 개의 Provider를 사용하게 되는 상황이 온다거나 할 때 확인하기가 더 쉬울 것 같더라구요!
<img width="760" alt="displayName 지정 예시" src="https://user-images.githubusercontent.com/62706988/192973898-9840bf01-db61-4eaa-8c23-379d0c43649c.png" />

2022-09-29 08:35 UTC, mina-gwak commented on src/components/common/RadioGroup/index.tsx
> +};
저도 다른 분들과 의견이 같습니다!
처음에는 꼭 필요한 옵션은 아니지만 함께 제공해줘도 괜찮지 않을까 하는 생각이었는데요. Radio 버튼 외에도 Input이나 Textarea 같은 폼 요소들을 Headless 컴포넌트로 계속 개발한다고 하면 해당 요소들에도 모두 Title이 필요할텐데 그렇게 중복으로 넣어줄 필요가 있을까 싶더라구요! 폼 요소들을 사용할 때 앞으로 만들 Text 컴포넌트를 활용해 Title을 작성한다던가 하는 방식으로 대신하면 되지 않을까 하는 생각이 들었습니당

2022-09-29 08:35 UTC, mina-gwak commented on src/components/common/RadioGroup/index.tsx
> +      <label htmlFor={optionId}>{children}</label>
저도 기본 Radio 버튼으로 되어있길래 커스텀을 할 수 있도록 하려면 수정이 조금 필요하지 않을까 싶었어요!
햄디가 어떤 구조로 작성하시느냐에 따라 다르겠지만 보통 Checkbox나 Radio를 커스텀할 때는 label을 많이 사용하니까 둘을 분리하지 않더라도 Option 컴포넌트의 구조에 따라 스타일을 커스텀할 수 있는 방식을 잘 가이드해주면 되지 않을까 했습니다!

2022-10-03 16:12 UTC, hemudi commented
### 221004 주요 변경 사항

<details>
<summary><h3>1. RadioGroup.Title 컴포넌트 제거<h3></summary>

PR 리뷰로 받은 의견대로 Title 컴포넌트의 필요성에 대해 고민을 해봤습니다.

그렇지않아도 구현한 Title 컴포넌트는 div 태그에 넘겨받은 props를 전달하여 반환할 뿐이라 단순히 div 태그에 Title이라는 이름을 붙인 것과 다를바가 없어 굳이 Compound Component로 구현할 필요가 있나 싶었습니다.

PR 리뷰를 받은 뒤 Radio Group의 예제들을 찾아보니 Title 요소를 단순히 div 태그 뿐 아니라 feildset과 함께 legend 태그로 쓰이거나(접근성에 좋음), label 컴포넌트를 써서 구현하는 경우도 있었습니다.

따라서 무의미한 Title 컴포넌트를 제공하는 것보단 사용자가 자유롭게 구현할 수 있게 하는게 좋을 것 같다는 생각 + PR 리뷰로 받은대로 RadioGroup에 필수적인 기능은 아니라고 판단되어 제거하였습니다.

</details>

<details>
<summary><h3>2. useMemo 제거 + RadioState 줄이기</h3></summary>

useMemo는 discussion에서 논의한대로 eslint 경고 옵션을 끄고 제거하였습니다.

그와 더불어 기존의 RadioState에서 name과 onChange는 Park 께서 짚어주셨던대로 **Title로 인해** children에게 간단히 props로 넘기기 쉽지 않았고, 어차피 RadioGroup의 모든 컴포넌트에서 사용 되어야 하는 값이니 그냥 context로 관리하자는 의도였습니다.

하지만 Title 컴포넌트를 제거하고 나니 간단히 Children.Map 으로 props를 넘길 수 있어 context로 관리하는 상태는 selectedValue를 제외하고 전부 제거하였습니다!

</details>

<details>
<summary><h3>3. Option 컴포넌트 with 커스텀 스타일</h3></summary>

PR 리뷰에서 Option 컴포넌트의 원활한 스타일 적용을 위해 input과 label을 분리하거나 추가적인 스타일 적용을 위한 방식이 필요해보인다는 리뷰를 받아 해당 부분에 대해 고민을 했습니다.

우선 Option 컴포넌트에 input과 label을 함께 두고 구현한 이유는 사용자의 편의성을 위해서였습니다.

하나의 라벨이 있는 라디오 버튼을 구현하면 input과 label을 각각 구현하고 동일한 id를 부여해줘야 하는데 그 과정이 제일 번거롭고 Radio Group의 코드를 복잡해 보이게 만드는 원인이라 생각해 단순히 Option 하위에 원하는 Label 컨텐츠만 추가해도 되도록 추상화하여 제공하고 싶었습니다. 

이후 Option 컴포넌트에 스타일을 입히는 부분은 사실 Headless 컴포넌트를 구현하면서 기능에만 집중하느라 스타일을 어떻게 입히는지는 제대로 고민하지 못했던 것 같습니다. 🥲

그래서 PR 리뷰로 받은대로 Option을 분리해서 각자 스타일을 적용해보거나, inputProps, labelProps등을 추가해보거나 여러 시도를 해봤는데...

9월 4주차 피어 세션에서 도니와 쨈에게 각각 스타일 적용 방법이 하나로 통일되면 좋겠다(현 프로젝트에서는 styled-components), 사용자에게 스타일 커스텀 방식을 잘 정의해서 제공해주기만 하면 괜찮을 것 같다는 리뷰를 받고 다시 처음으로 돌아가 여러 방식으로 스타일을 적용해봤습니다.

   **그 결과..._기존의 Option 코드에서 아무것도 변하지 않았습니다! ㄴ( x o x )ㄱ_**

그 대신 기존에는 스스로도 확답 할 수 없었던 커스텀 방식을 아래와 같이 정의하여 권장 하기로 하였습니다.

   ```tsx
   const StyledRadioOption = styled(RadioGroup.Option)`
     // Custom div(Wrapper) Style
     
     input[type='radio'] {
       // Custom Radio Button Style
     }
   
     label {
       // Custom Label Style
     }
   `;
   ```
css 선택자를 이용해 내부의 input과 label에 접근하는 방식인데 애초에 RadioGroup 컴포넌트가 많은 기능이나 복잡한 구조를 가지고 있지 않기 때문에 해당 방식이면 충분히 왠만한 스타일을 커스텀 할 수 있을거라 결론 지었습니다.

실제로 다양한 스타일을 예제를 참고하거나 구상해 적용을 시도해보았고([CodeSandBox](https://codesandbox.io/s/headless-radiogroup-nml52g?file=/src/radioGroup.styled.tsx)) 이 정도 커스텀이면 충분하다 판단하여 라디오 그룹 컴포넌트는 큰 문제가 없는 한 이쯤에서 마무리할까 합니다!

**RadioGroup에 대한 추가적인 스타일링이나 내부 로직에 대한 이슈는 이슈 발생 시 그때 대응하도록 하겠습니다!**
</details>

---
별로 복잡하지 않은 컴포넌트에 너무 많은 시간을 투자(~~_삽질_~~)한 것 같네요....
Headless 컴포넌트의 학습비용이라 생각하고 Input 컴포넌트부턴 분발하여 학습한 내용들을 토대로 속도를 올려 개발해보겠습니다!ㅠ_ㅠ)9

+) 시간 되실 때 확인 해주시면 감사하겠습니당! @healtheloper

2022-10-03 17:21 UTC, healtheloper approved these changes
👍

2022-10-03 17:21 UTC, healtheloper commented on src/components/common/RadioGroup/index.tsx
> +    }
isValidElement 가 ReactElement 인지 확인하는? 그런 로직이었던걸로 기억하는데, 이게 의미가 있는 작업인지 궁금했어서 저는 덜어냈었거든요, 관련한 이슈가 있었는지 궁금하네요 🧐

2022-10-03 17:41 UTC, hemudi commented on src/components/common/RadioGroup/index.tsx
> +    }
![스크린샷 2022-10-04 오전 2 30 04](https://user-images.githubusercontent.com/34249911/193641276-7bf5c205-f91d-4c16-a576-cbd1e6ab8eea.png)
제 환경에서는 위와 같이 구현을 하려다 children이 ReactNode 타입으로 되어 있는 탓에 cloneElement의 child 타입 `ReactElement<~>` 와 맞지 않는다는 type error가 발생하였습니다!
그래서 해결 방법을 찾아보니 as ReactElement 로 타입을 변환해주거나 isValidElement로 체크해주는 방법이 있었는데, 명시적으로 체크를 해주는 것이 안전하지 않을까 하여 isValidElement를 사용하는 방식을 선택했습니다.([stackoverflow](https://stackoverflow.com/a/42261933))

2022-10-05 04:53 UTC, merged