[Dony] Text 컴포넌트
Co-Studo/Co-Studo-front pull request #58
Opened 2022-10-13 23:37 UTC by jindonyy

close #23 

고민이 많아지다 늦어졌네여 ㅎ-ㅎ;
코드는 딱히 어려운건 없어 고민했던 부분만 적어놓겠습니다!

## 구현 설명
### variant prop
- 정해져있는 폰트 스타일 사용할 시
### sx prop
- variant에 없거나 조금 수정하여 사용할 시
- font관련 스타일을 받을 때는 fonts에서 정해둔 키 값만을 받기 위해 타입 제한을 두었습니다.
- render prop으로 원하는 태그로 바꿀수 있으니 다른 style도 받을 수 있게 해야하나 고민 중..
### render prop
- Text에 사용하고 싶은 element
- as prop 대신 태그를 바꿨을 때 자신이 추가하고싶은 attribute(data, a 태그 시 href, ..)도 추가하여 사용할 수 있도록 render prop 패턴을 이용

<br>

## 고민한 점
### typography
MUI를 참고해서 처음에는 h1, h2, .., description1, ..., button1,.. 이런 식으로 했었습니다.
디자인을 보면 '참여중인 스터디'와 같은 폰트들이 전부 h2로 들어갈 내용들이고, StudyCard 안에 '스터디 이름'과 같은 폰트들이 아티클의 제목으로 보여 h3로 쓸 수 있겠다는 생각이 들어서요.
그런데 아래 사진의 부분은 h 태그보단 dt 태그가 더 어울릴거 같단 생각도 들어 h2, h3 등의 이름을 붙이면 해당 태그에만 사용하라 한정인 것 같아보일수도 있겠다 생각했습니다. (다르게 써도 상관은 없습니다. 그저 레이아웃이니!)
<img width="318" alt="스크린샷 2022-10-14 오전 8 10 05" src="https://user-images.githubusercontent.com/17706346/195726934-ea4330a2-15bc-4316-b8b9-eb0c86b88b17.png">
그래서 역할에 맞는 이름으로 변경했지만 아직도 고민입니다..@_@
(왜냐, 스터디 생성 페이지는 타이틀이 하나라 sectionTitle보다는 heading이 맞는거 같아서..)
고민이 많아서 죄송합니다. 😂

### typography에 button
버튼과 관련된 폰트도 정해져있기 때문에 typography에 넣었는데 응집도면에서 버튼의 스타일에 있어야하나 싶습니다. 그런데 버튼 스타일에 추가하게 되면 글자가 들어가는 경우 Text 컴포넌트를 쓰기로 했으니 여기서 사용하는게 맞지 않나 생각하여 추가했습니다.

### fonts, typography 파일의 위치
둘 다 Text 컴포넌트에서 사용하여 Text 폰트에 뒀었지만 GlobalStyle에서도 fonts에 지정한 속성을 사용해야해서 theme으로 옮겼습니다. 그래서 theme의 폴더명을 styles로 바꾸는건 어떨까요??

2022-10-14 02:36 UTC, healtheloper requested changes
수고하셨습니다 도니!!
의논해보고 싶은게 있어서 Request changes 로 남겨놓을게요~

2022-10-14 02:36 UTC, healtheloper commented on src/app.css
> +  font-family: 'Noto Sans KR';
제 기억상으로는 전 방법으로도 폰트가 적용된걸로 기억하는데, 바꾸신 이유가 있을까요?

2022-10-14 02:36 UTC, healtheloper commented on src/components/common/Text/index.tsx
> +};
style type 이 뭔지 몰라서, 여기에 뭐가 들어가야할지 감이 잘 안오네요

2022-10-14 02:36 UTC, healtheloper commented on src/components/common/Text/index.tsx
> +  color?: keyof IPalette;
color 는 palette 에 지정된 색 외에도 쓰고싶을 수도 있지 않을까.. 란 생각이 있습니다. ( warning, danger 이외에 초록색 이름은 뭐로..? )

2022-10-14 02:36 UTC, healtheloper commented on src/components/common/Text/index.tsx
> +  const getVariantStyle = () => variant && typography[variant];
기본 variant 를 설정해놓고, textStyle 에서 바로 ...typography[variant] 로 써도 되지 않을까요?

2022-10-14 02:36 UTC, healtheloper commented on src/components/common/Text/index.tsx
> +  return render(textStyle);
Text 컴포넌트를 사용하는 곳에서 모두 render 라는 함수를 지정해서 넘겨줘야하고, style 이라는 param 도 항상 넘겨줘야 하나요?

사용자가 Text 컴포넌트를 사용할 때 기대하고 있는 기본 동작이 있을텐데, 그것을 사용자가 지정해줘서 넘겨줘야하나? 라는 생각이 들었습니다, 

해당 방식이 render prop 패턴을 사용하기 위해 쓴거고, 추가하고 싶은 attribute 를 사용하고 싶었던 거라면 -> a 태그를 쓰고 싶다면 a 태그의 자식으로 Text 를 사용하면 되고, data 는 Text 에서 사용할 일이 있을지? 싶었습니다. 

제가 기대했던건 h1, h2, h3, h관련... , span 정도의 Text 관련 태그를 사용할 수 있음을 생각했던 것 같아요

2022-10-14 02:36 UTC, healtheloper commented on src/components/common/Text/index.tsx
> +  };
사용자가 sx prop 을 통해서 custom 하게 사용할 일은 만들어진 것 이외에 예외적인 상황에서 쓴다고 생각이 드는데 만들어놓은 fonts 내로 제한한다면 큰 의미가 있을지? 라는 생각이 들었습니다.

2022-10-14 15:25 UTC, jindonyy commented on src/app.css
> +  font-family: 'Noto Sans KR';
아..! 되긴하는데 글자가 붙어있으니 폰트명을 읽기 힘들어 원래 폰트명처럼 띄웠어요..😅
작은 따옴표는 css 컨벤션 중에 외부에서 불러오는 부분은 작은 따옴표를 붙이는 컨벤션이 있어 (src와 background-image에 url도 작은따옴표 없이도 되지만 붙이는 이유)거기에 맞게 수정을 했는데 논의하지 못하고 수정했네요ㅠㅠ! 혹시 다른 의견있으시면 말해주세요~!

2022-10-14 16:16 UTC, jindonyy commented on src/components/common/Text/index.tsx
> +  color?: keyof IPalette;
엇.. 지난번에 제가 color를 provider에 넣지 않으면 palette에 없는 색을 사용해야 할 떄는 import 해와서 사용해야 하냐고 질문드렸는데 색상을 사용할 때는 palette에서만 쓰는게 맞지 않나 생각한다고 하셔서 그렇게 했습니다..!

2022-10-14 16:16 UTC, jindonyy commented on src/components/common/Text/index.tsx
> +};
아래에 render 함수에 파라미터로 넘겨주는 값(여기서는 textStyle)이 들어오는 패턴이라 알지 않을까 해서 따로 지정하지 않았어요. render prop을 모르는 상태로 봐도 알도록 추가해야겠네요!

2022-10-14 16:16 UTC, jindonyy commented on src/components/common/Text/index.tsx
> +  const getVariantStyle = () => variant && typography[variant];
variant의 default를 해야한다면 typography에서 body부분이 적절하다고 생각하는데요. 그런데 font 속성은 inherit 되야하는데 variant의 default를 지정하면 부모의 폰트를 물려받지 못하고 항상 body 폰트가 default로 되버립니다. 때문에 variant를 지정안했다 -> 부모의 폰트를 쓰겠다 라 지정해놓는게 좋다고 생각해요!

2022-10-14 16:16 UTC, jindonyy commented on src/components/common/Text/index.tsx
> +  };
커스텀의 확장을 어디까지로 할지 정해야한다고 생각하는데요. 저도 예전에 라이브러리처럼 지정된 스타일 외에도 커스텀 할 수 있도록 다양하게 커스텀 기능을 추가해서 컴포넌트를 만든적이 있습니다.
그 이유는 운영을 하다보면 어쩔수 없이 기존 디자인이랑 조금 다르게 해야하는 경우가 간혹 생겨서 였어요. 디자인 시스템이 잘 되어있는 디자인이라면 현재 디자인에서 사용하고 있는 폰트 외에 다른 폰트가(14px, 16px, 18px 등을 사용하다가 갑자기 17px로 디자인이 되었다.) 들어오는 경우가 없는게 맞고 이런 경우가 생긴다면 디자이너의 의도가 뚜렷하지 않는 한 수정 요청을 해야한다고 생각합니다. (개인적으로 디자이너가 원하는대로 구현하는게 맞지만, 디자인 시스템이 정해져있는 부분인데 다를 경우 의도한건지 여쭤봐야한다고 생각해요.)
추후에 운영을 생각하여 커스텀을 확장한다면 말씀해주시는 방법이 좋고, 애자일하게 현재의 구현에 집중을 한다면 지금처럼 디자인 시스템에 맞게가 좋은거 같아요!

2022-10-14 19:45 UTC, jindonyy commented on src/components/common/Text/index.tsx
> +  return render(textStyle);
음.. 태그 중첩을 줄이기 위해서 font css를 번경하고 싶은 element를 다 사용하게 하려고 했었던 의도였어요. 리액트를 사용한 사이트를 보면서 느낀점은 스타일을 위한 중첩이 많다였어요. 그래서 font css 번경이라는 역할만 가지고 있자라고 의도했었습니다.
그런데 컴포넌트 기반이니 어쩔수 없는 부분이란 생각도 드네요. Text라는 컴포넌트명에 맞게하려면 인라인 태그들만 사용할 수 있게 하는게 맞는거 같아요. h태그도 text라는 이름에는 맞지 않는거 같아 span, em, strong 등 인라인 태그로 as 해서 사용할 수 있는게 좋을거 같아요!

2022-10-15 06:58 UTC, healtheloper commented on src/app.css
> +  font-family: 'Noto Sans KR';
아하 그런 컨벤션이 있었군요 몰랐습니다..!
혹시 그런 컨벤션 가이드가 어디서 권장되는건지? 알 수있나요?

2022-10-15 06:59 UTC, healtheloper commented on src/components/common/Text/index.tsx
> +  color?: keyof IPalette;
다시 생각해보니까 palette 를 통해 제한하는게 맞는 것 같아요, 모두가 일관된 방식으로 색상을 입혀야 하니까요

2022-10-15 07:02 UTC, healtheloper commented on src/components/common/Text/index.tsx
> +  };
좋아요, sx 라는 prop 의 사용법에 대해 고민이 생기네요

2022-10-15 07:10 UTC, healtheloper commented on src/components/common/Text/index.tsx
> +  const getVariantStyle = () => variant && typography[variant];
string 을 표현해야 하는 곳을 모두 Text component 를 통해 표현하면 font 속성을 inherit 해서 써야할 상황이 있을까요?

variant 를 지정 안했다 -> 부모의 폰트를 쓰겠다 지정을 해 놓는다는거면, variant 에 어떤 값을 넣어야 하는건지 주어진 story 로는 잘 모르겠어서 예시를 들어주실 수 있나요?

2022-10-15 07:16 UTC, healtheloper commented on src/components/common/Text/index.tsx
> +  return render(textStyle);
`태그 중첩을 줄이기 위해서 font css 를 변경하고 싶은 element 를 다 사용하게 하려했다` 라는 부분이 잘 이해가 되지 않는데요 ㅠ..
문제가 될만한 부분과 그 개선을 어떻게 하시려고 하셨는 지 알려주실 수 있을까요? children 으로 string 을 넣는 방식으로 생기는 문제가 있나요?

heading tag 가 text 의 의도로 사용되는건 맞지 않다고 생각하시는 걸까요?

render 라는 prop 을 전달해서 사용하는 패턴이 결국 Text component 를 쓰는 모든 곳에서 `(style) => <tag style={style}></tag>` 와 같은 형식을 반복적으로 사용해야 하는데, 이를 내부 로직으로 숨겨서 사용하는 곳에선 간편하게 사용하는게 좋지 않을까요?

2022-10-16 21:14 UTC, jindonyy commented on src/app.css
> +  font-family: 'Noto Sans KR';
예전에 읽은거는 [NHN css convention](http://www.tutor4u.co.kr/data/member/test16.pdf)(위의 내용은 52페이지)에서 읽었던 내용이예요. 지금보니 폰트는 외부에서 불러와서가 아니라 띄어씌가 있어서였네여ㅎㅎ;
이거말고 css 속성 순서는 [Mozilla 컨벤션](http://milooy.github.io/TIL/CSS/css-property-order.html#intro)으로 맞추려고 합니다.
근데 저도 NHN 규칙을 다 따르진 않고 거의 이 분이 작성해놓은 [규칙](https://jeonghakhur.gitbooks.io/frontend-coding-convention/content/css/)을 따르긴 해요! 제 기준 가독성 제일 좋은 규칙이라 생각해서요!

2022-10-16 21:30 UTC, jindonyy commented on src/components/common/Text/index.tsx
> +  const getVariantStyle = () => variant && typography[variant];
부모의 폰트를 따르지만 size나 weigth 만 변경하고 싶은 경우에도 Text 컴포넌트를 써야한다고 생각했어요.
default로 body를 해놓는 경우 size, weigth, family, stye, .. 등등 모두 body 폰트를 따르게 되는데 부모의 폰트를 따르면서 size만 변경하고 싶은 경우 size외에 전부 inherit으로 지정을 해줘야해서 번거롭다고 생각이 들어요. 저희가 폰트 스타일을 변경할 때 변경하는 값들은 일부니까..?
```tsx
// variant의 default가 body인데 부모의 폰트에서 size만 바꾸고 싶은 경우
<Text
  sx={{ fontSize: 'large', fontWeight: 'inherit', fontFamily: 'inherit', fontStyle: 'inherit', line-height: 'inherit', ...}}
  render={(style) => <h2 style={style}>스터디 생성</h2>}
/>
```

2022-10-16 21:36 UTC, jindonyy commented on src/components/common/Text/index.tsx
> +  return render(textStyle);
<s>요건 제가 다시 남기고 태그 하겠습니다..!</s>

2022-10-17 03:20 UTC, mina-gwak approved these changes
> 그런데 아래 사진의 부분은 h 태그보단 dt 태그가 더 어울릴거 같단 생각도 들어 h2, h3 등의 이름을 붙이면 해당 태그에만 사용하라 한정인 것 같아보일수도 있겠다 생각했습니다. (다르게 써도 상관은 없습니다. 그저 레이아웃이니!)
> 그래서 역할에 맞는 이름으로 변경했지만 아직도 고민입니다..@_@

저도 태그 이름보단 역할에 맞는 이름이 좀 더 적합하지 않을까 싶어요! 말씀하신 것처럼 같은 스타일을 가지고 있는 텍스트라도 링크가 걸려야 한다면 a 태그를 사용하는 등 달라질 수 있는 부분이 있기 때문에 도니가 작성하신 방식이 더 나은 것 같다는 생각이 드네요.

> 버튼과 관련된 폰트도 정해져있기 때문에 typography에 넣었는데 응집도면에서 버튼의 스타일에 있어야하나 싶습니다.

이 부분도 동의해요! 버튼에서 사용되기는 하지만 텍스트의 스타일에 관련된 내용이기 때문에 텍스트 쪽에 있는 게 맞는 것 같습니당

> 둘 다 Text 컴포넌트에서 사용하여 Text 폰트에 뒀었지만 GlobalStyle에서도 fonts에 지정한 속성을 사용해야해서 theme으로 옮겼습니다. 그래서 theme의 폴더명을 styles로 바꾸는건 어떨까요??

처음엔 theme 폴더에는 테마 관련 파일만 두고 두 파일을 Text 컴포넌트에 놓는 게 낫지 않을까 싶었는데 생각해보니 GlobalStyle 파일도 theme 폴더에 있고, 그렇다고 테마 관련 파일을 두는 theme과 스타일 관련 파일을 두는 styles를 분리하자니 그것도 좀 애매하다는 생각이 드네요. 말씀하신 것처럼 다 한 폴더에 두고 styles로 변경하는 것도 괜찮은 것 같습니다!

마지막으로 저도 파크가 말씀하신 것처럼 render prop을 항상 넘겨줘야 하는 방식이 좀 불편하지 않을까 싶었어요! 그리고 도니가 남기신 코멘트를 보니 예를 들어 a 태그 안에 Text 컴포넌트를 넣으면 단지 스타일을 위해 태그를 중첩해서 쓰게 되는 거니까 이런 부분을 줄이기 위해 Text 컴포넌트에 건네주는 요소에 스타일을 입히는 용도로만 쓰려고 하셨던 게 아닐까 싶었는데요..! (제가 이해한 게 맞나요..? 아니라면 죄송합니다 🥲) 좋은 아이디어이긴 하지만 그렇게 되면 이름처럼 Text를 반환하는 컴포넌트라기보다는 전달받은 요소에 스타일을 입혀서 반환하고 있으니까 좀 다른 네이밍을 해줘야 하지 않을까 하는 생각이 들었습니당!

작성하신 PR 보니 고민이 많으셨을 것 같은데 고생 많으셨습니다 도니 👏

2022-10-17 03:20 UTC, mina-gwak commented on src/components/common/Text/index.tsx
> +    });
어차피 key와 value 모두 사용할 거라면 Object.entries를 사용해도 되지 않을까 하는 생각이 들었습니다!

```suggestion
    Object.entries(customStyle).forEach(([key, value]) => {
      customStyle[key] = 
        key === 'color' ? theme.palette[value] : fonts[key][value];
    })
```

2022-10-17 03:57 UTC, healtheloper commented on src/components/common/Text/index.tsx
> +  const getVariantStyle = () => variant && typography[variant];
저는 Text 에 inherit 를 해야할 상황이 어떤 상황에 써야하는지 감이 오지 않아서, 혹시 inherit 를 넣기 위해 생각했었던 상황이 있으셨는지 궁금합니다, 

만약 inherit 가 필요하다면 variant 에 inherit 를 넣고 필요한 sx 만 넣는 방식도 있을 것 같아요.

2022-10-17 04:58 UTC, hemudi approved these changes
> 그래서 역할에 맞는 이름으로 변경했지만 아직도 고민입니다..@_@
(왜냐, 스터디 생성 페이지는 타이틀이 하나라 sectionTitle보다는 heading이 맞는거 같아서..)

확실히 태그로 이름을 붙이면 말씀하신 것처럼 특정 태그에만 제한적인 느낌이 들고 태그가 같아도 적용되는 스타일이 다른 경우가 있을 수 있으니 현재 방식이 좋은 것 같아요! ^_^)b 찬성입니다!

> 그래서 theme의 폴더명을 styles로 바꾸는건 어떨까요??

저도 위에 제이미께서 남겨주신 리뷰대로 딱 이렇다 하게 구분하기 어려운 것 같아 우선은 styles라는 범용적인 폴더 내에 함께 두고 관리하다가 추후 분리가 필요하다 느껴질 때 다시 고민해봐도 좋을 것 같아요!

> render props 패턴

render props 부분의 첫인상은 저 또한 사용하는데 조금 불편한 부분이 있지 않을까 싶지만 아직 도니의 의도를 명확히 파악하지 못해서 도니께서 추후 덧붙여주시는 설명을 보고 조금 더 생각을 해봐야 될 것 같네요!

간단한 컴포넌트라고 하더라도 잘 구현하기 위해서는 그만큼 많은 고민을 해야하는 것 같아요!
도니의 고민에는 늘 합당한 근거가 있고, 늘 그에 따른 결과물이 나오니 저는 도니의 깊은 고민을 지지합니다! 

고생 많으셨습니다! ^_^)9

2022-10-17 04:58 UTC, hemudi commented on src/theme/GlobalStyle.ts
> +    font-size: 62.5%;
별거 아닐 수 있긴한데 혹시 퍼센트 숫자가 무엇을 의미하는지 주석을 추가하는건 어떨까요?
저희끼리는 합의하여 무엇을 의미하는지 명확히 알긴하지만 그래도 좀 어떤 역할을 하는지 한번에 유추하기 어려운 특수한 값이라는 생각이 들어서요!
만약 주석을 추가한다면 함께 논의했던 [discussion 주소](https://github.com/Co-Studo/Co-Studo-front/discussions/53)를 주석으로 추가해도 괜찮을 것 같아요

2022-10-18 00:01 UTC, jindonyy commented on src/components/common/Text/index.tsx
> +  const getVariantStyle = () => variant && typography[variant];
1. inherit이 필요한 상황
(예시를 위해 render prop말고 as로 해놓겠습니다.)
부모가 가지고 있는 font-size, font-weight, line-height를 그대로 가지고 가면서 color만 바꾸고 싶을 경우
```tsx
<Text variant="sectionTitle" sx={{lineHeight: 1}} as="p">
  스터디
  <Text sx={{color: 'primary'}} as="span">생성</Text>
  페이지입니다.
</Text>
```
2. default로 inherit을 넣을 경우
font 속성은 어차피 inherit 될건데 굳이 써야하나 싶어요.
inherit을 추가할 경우 아래처럼 inherit 코드들이 추가되는데 지정해주지 않아도 inherit되는데 굳이 적어서 코드를 늘려야하나? 싶어요. 그리고 저렇게 할 경우 css 코드를 꺼보면서 디버깅할 때 위에 inherit 코드 때문에 실제로 물려받는 부모의 css 코드가 취소선 쳐져서 적용되어 있는 폰트를 찾기가 조금 어려워?지더라구요. 때문에 저는 inherit은 a 태그처럼 브라우저 스타일로 인해 부모의 폰트를 받지 못할 때만 지정하는 편이예요.
(예시는 스토리북에 추가해놓을게요!)
<img width="1048" alt="스크린샷 2022-10-18 오전 8 54 39" src="https://user-images.githubusercontent.com/17706346/196304860-1d125603-1f02-4de7-83f1-7ddbf81fd316.png">

2022-10-18 03:19 UTC, healtheloper commented on src/components/common/Text/index.tsx
> +  const getVariantStyle = () => variant && typography[variant];
강조단어도 Text 컴포넌트를 통해서 표현해야할까요?
강조단어가 부모 자식간의 관계를 유지해야 한다면 강조를 위한 컴포넌트를 하나 더 만드는게 어떨까요?
혹은 여러개의 Text Component 를 사용할 수도 있긴 할 것같은데, 피하신 이유가 있나용?

```tsx
<Text> 여기는 문장이고, <Text.Bold>강조단어</Text.Bold> 입니다. </Text>

<Text> 여기는 문장이고 </Text>
<Text sx={{ color: 'primary' }}> 강조단어 </Text>
<Text> 입니다. </Text>
```

2022-10-18 04:12 UTC, healtheloper commented on src/components/common/Text/index.tsx
> +  return render(textStyle);
저는 Text 가 variant 같은 것을 통해서 표현해준다면 heading text 의 의미로도 쓰일 수 있지않을까 싶었어요
그리고 애초에 리액트에서 a 태그를 쓸 일이 없을 것 같아서 a 태그가 고려사항엔 없다고 생각하구요

button 같은 경우는 중첩해서 쓸 수는 있긴 할텐데, 스타일을 입히기 위한 중첩이라면 필요하다고 생각하는데 어떤 부분에서 불필요하다고 생각하셨나요?

2022-10-18 09:03 UTC, jindonyy commented on src/components/common/Text/index.tsx
> +  const getVariantStyle = () => variant && typography[variant];
강조 스타일이라는게 태그마다 다르듯이 좀 범위가 광범위한거 같아요.
em, i 태그 같은 경우 이탈릭체로 강조할 때, strong, bold 태그는 굵기로 강조할 때 사용하고, 컬러로 강조하고 싶은 경우도 있을텐데요.
이럴 경우 나머지 폰트 속성은 강조하지 않은 문장과 같고 어느 style, weight, color 중에 한두개만 다를테니 강조하지 않은 문자의 폰트를 물려받을 수 있도록 중첩되는게 맞는거 같아요.
그리고 bold로 따로 뺴는건 좋은 아이디어같아요. bold로 한다면 as를 em, i, strong, bold로 한정지어 놓고 해당 태그로 지정하면 기울기나 볼드가 적용되게 하는거도 괜찮을거 같네요! (그런데 as를 구현하는게 좀 어려워서 한정지을수 있을지 모르겠네여 ^_ㅠ) 그리고 color로 강조하는 태그는 따로 없어서 color는 sx로 받아서 하는게 맞는거 같아요!

2022-10-18 09:08 UTC, healtheloper commented on src/components/common/Text/index.tsx
> +  const getVariantStyle = () => variant && typography[variant];
일단 저희 프로젝트의 디자인 내에서는 다양한 강조 스타일을 고려하진 않고 있으니 필요한 경우 따로 빼서 사용하는게 어떨까 싶습니다!
강조단어는 태그가 정해져있으니 as 를 고려할 필요도 딱히 없을 것 같구요

일단 디자인에서 사용될 법한 내에서 고려하면 되지 않을까 싶어요~

2022-10-18 09:17 UTC, jindonyy commented on src/components/common/Text/index.tsx
> +  return render(textStyle);
> a 태그를 쓸 일이 없을 것 같아서 a 태그가 고려사항엔 없다고 생각하구요

음.. a태그는 저희 체크아웃 글올릴 때 참조 링크를 걸어두는 글이 많아서 자주 쓰일거 같긴해요. 물론 저희 디자인시스템을 따르는건 아니지만?

> button 같은 경우는 중첩해서 쓸 수는 있긴 할텐데, 스타일을 입히기 위한 중첩이라면 필요하다고 생각하는데 어떤 부분에서 불필요하다고 생각하셨나요?

위의 설명과 같이 그냥 a 나 button에 스타일을 적용해도 될텐데 텍스트의 스타일 일부 변경을 위해 span을 사용하는게 아니라 button 전체에 스타일을 적용해야하는게 불필요해보였어요.
```tsx
// 파크가 말하는 중첩
<Button type="button"><Text variant="buttonM" as="span">스터디 생성하기</Text></Button>

// 제가 생각하는 span의 역할
<Text variant="buttonM" as="button">스터디 <Text sx={{color: "primary"}} as="span">생성</Text>하기</Text>
```
그런데 이렇게 할 경우 Button 태그를 재사용 못하긴 해요ㅠ 컴포넌트로 재사용하는 리액트 특성상 리액트로 된 페이지들을 보면 스타일을 위한 중첩이 많이 생기긴 하더라구요. 예전에 카카오페이지 때도 느꼈습니다.
button이랑 a만 빼도 될거 같아요! 두 태그의 특성이 좀 더 다른거 같긴하네용

2022-10-18 09:23 UTC, jindonyy commented on src/components/common/Text/index.tsx
> +  const getVariantStyle = () => variant && typography[variant];
음.. color로 강조된게 다긴하네요. 우선 순위를 낮춰도 되겠어요~
넴 그럼 variant의 default는 안하는걸로..? (어쩌다 여기까지 흘러왔네여 ㅎㅎ;)

2022-10-18 09:31 UTC, healtheloper commented on src/components/common/Text/index.tsx
> +  return render(textStyle);
> 참조 링크를 걸어두는 글이 많아서

헉 이건 제가 놓쳤네요 죄송합니다 😂

말씀하신 것 처럼 Text 컴포넌트에 button 을 as 로 넣는게 생소한 느낌이 들어서 as 로 수정하시고 계신 것을 참고해보겠습니다

2022-10-18 09:37 UTC, healtheloper commented on src/components/common/Text/index.tsx
> +  const getVariantStyle = () => variant && typography[variant];
default 를 body 정도로 해야하지 않을까요? default 를 하지 않으려고 했던 이유가 inherit 적용을 해야하는 상황에서 할 수없다는 것 이었는데
inherit 가 필요한 상황 -> Text.Bold (얘는 default 가 body가 아님) 등으로 해결되지 않을까 해서요

2022-10-18 10:21 UTC, jindonyy commented on src/components/common/Text/index.tsx
> +  const getVariantStyle = () => variant && typography[variant];
위에서 말했듯이 일단 강조를 하려면 중첩을 해야하자나요.
> 이럴 경우 나머지 폰트 속성은 강조하지 않은 문장과 같고 어느 style, weight, color 중에 한두개만 다를테니 강조하지 않은 문자의 폰트를 물려받을 수 있도록 중첩되는게 맞는거 같아요.
문장 중에 강조를 한다고 치면
```tsx
<Text as="p"> 여기는 문장이고, <Text.Bold as="strong">강조단어</Text.Bold> 입니다.</Text>
```
때문에 부모인 p 태그의 폰트를 따르고 weight만 변경하고 싶은데 default를 body로 하면 weigth외에는 부모가 아니라 body의 폰트를 따르게 default를 하려면 inherit이 더 나을거 같다고 말씀드린거구
하지만 inherit을 할 경우 필요없는 중복코드가 생간다고 말씀을 드린거예요.

2022-10-18 12:28 UTC, healtheloper commented on src/components/common/Text/index.tsx
> +  const getVariantStyle = () => variant && typography[variant];
prop 없이 프로젝트 내부에서 span 을 대신할 목적으로 Text 컴포넌트를 쓸 수 있다고 생각하는데,
그 Text 의 기본동작을 기대하는 면에서 default 가 없으면 Text 컴포넌트에게 기대하는 기본 동작이 없을거라고 생각했습니다

Text.Bold 가 default 를 body 나 inherit 를 가지는 컴포넌트가 아니라 weight 만 변경하는 컴포넌트라면 inherit 관련 중복코드도 안생기게 할 수있을 것 같아 말씀드렸어요!

```tsx
const Bold = ({ children }) => {
  return <b>{children}</b>;
};

Text.Bold = Bold;
```
코드 마무리 되시고 사용해보면서 의논해도 좋을 것 같습니당

2022-10-24 09:33 UTC, healtheloper approved these changes
고생하셨습니다 도니~
현재 dev 랑 conflict 가 나서 rebase 해주셔야할 것 같아요

2022-10-24 09:33 UTC, healtheloper commented on src/components/common/Text/index.tsx
> +  };
sx 를 제한하기로 했으니, switch 문 등으로 key 에 따라 원하는 value 를 얻는 helper 를 하나 만들 수도 있겠네요

또한 객체를 선언하고 그 객체의 값을 바꿔주는 방식 보다는 바로 reduce 등을 통해 return 하는게 더 나을 듯 합니다.

```tsx
 const getCustomStyle = (sx) => (
    Object.entries(customStyle).reduce((acc, ([key, value])) => {
     acc[key] = key === 'color' ? theme.palette[value] : fonts[key][value];
     return acc
    }, {});
);
```

객체를 key 값을 통해 value 를 바꾸는게 lint 로 막혀있는 rule 도 있을건데 해당되는 코드가 아닌가보네요?!

2022-10-24 09:33 UTC, healtheloper commented on src/components/common/Text/text.stories.tsx
> +      </Text>
저번 리뷰에서 언급했던 부분이긴 한데 Text 에 Compound 형식으로 따로 빼내어 사용하면 inherit (+ 태그를 string 으로만 쓴다면 as 도) 부분을 추상화할 수 있다고 생각합니다.

```tsx

const Bold = ({sx, children}) => {
  const boldCss = getCustomStyle(sx)
  
  return (<strong css={boldCss}>{children}</strong>)
}

Text.Bold = Bold

<Text.Bold sx={{ color: 'warning' }}>강조단어</Text.Bold>
```

2022-10-24 09:33 UTC, healtheloper commented on src/styles/typography.ts
> +  },
얘만 fontSize 가 여기있는데, 수정할 때 fonts, typography 를 왔다갔다 하게 될 것같아서,

xxlarge 정도로 설정하면 어떨까 생각이 듭니다

2022-10-24 16:55 UTC, jindonyy commented on src/components/common/Text/index.tsx
> +  };
> sx 를 제한하기로 했으니, switch 문 등으로 key 에 따라 원하는 value 를 얻는 helper 를 하나 만들 수도 있겠네요

지금 sx가 font 관련 속성만 들어오게 type 설정해뒀는데 이걸 말한게 맞을까요..?

> 또한 객체를 선언하고 그 객체의 값을 바꿔주는 방식 보다는 바로 reduce 등을 통해 return 하는게 더 나을 듯 합니다.

👍

> 객체를 key 값을 통해 value 를 바꾸는게 lint 로 막혀있는 rule 도 있을건데 해당되는 코드가 아닌가보네요?!

그건 파라미터로 넘어온 객체 바꿀때만 아닐까여..?

2022-10-24 16:57 UTC, jindonyy commented on src/components/common/Text/text.stories.tsx
> +      </Text>
> 코드 마무리 되시고 사용해보면서 의논해도 좋을 것 같습니당

이게 차차 필요할 때 만들자는건 줄 알았네여 ^_ㅠ
bold도 추가할께요~!

2022-10-25 05:56 UTC, healtheloper commented on src/components/common/Text/text.stories.tsx
> +      </Text>
좋아요, 그럼혹시 variant 에 inherit 가 더 필요할까요?

2022-10-25 06:25 UTC, healtheloper commented on src/components/common/Text/index.tsx
> +  };
> 지금 sx가 font 관련 속성만 들어오게 type 설정해뒀는데 이걸 말한게 맞을까요..?

```tsx
acc[key] = key === 'color' ? theme.palette[value] : fonts[key][value];
```

이 부분이 현재 color, font 로만 제한되어 있어서 다른 경우도 있지 않을까 해서 따로 분류하는걸 말씀드렸습니당

2022-10-25 08:46 UTC, jindonyy commented on src/components/common/Text/text.stories.tsx
> +      </Text>
혹시 font: inherit을 써본적이 있으신가요..?? 저는 button, a 처럼 font 속성을 따로 가지고 가는 태그에 지정해줄 때 외에는 inherit을 써본적이 잘 없어요. 왜냐하면 지정 안해줘도 inherit이 되기 때문에요. 때문에 사용자가 variant를 지정 안했다 -> variant에 있는 typography 말고 sx로 지정해서 몇개만 쓰겠다 -> sx로 지정한 외에는 inherit 하겠다 -> inherit은 지정해주지 않아도 default로 된다.
이 흐름이고 사용자가 기대하는 기본 동작인 inherit은 Text 내부에서 지정해주지 않아도 되기 때문에 굳이 코드양을 늘릴 필요가 없다고 생각해요~!
default로 되는데 defaul value를 또 지정하는 느낌입니다!

2022-10-25 09:08 UTC, mina-gwak approved these changes
변경된 방식이 좀 더 간편하게 쓸 수 있어서 좋은 것 같아요!
고생하셨습니다 도니 😄😄

2022-10-25 09:08 UTC, mina-gwak commented on src/components/common/Text/index.tsx
> +`;
요 부분을 따로 작성하지 않고 위에 작성한 StyledText로 대체해도 되지 않을까요? 받는 prop이나 스타일을 적용해주는 부분이 동일하기도 하고 Highlight도 Text에 포함되는 개념이긴 하니까 괜찮지 않을까 싶네요!

2022-10-25 09:10 UTC, mina-gwak commented on src/components/common/Text/text.stories.tsx
> +      </Text>
저도 도니 말씀에 동의합니다! inherit은 기본적으로 설정되는 값이니까 굳이 한번 더 지정해줄 필요는 없다는 생각이 드네요!

2022-10-25 09:11 UTC, jindonyy commented on src/components/common/Text/index.tsx
> +  };
> 이 부분이 현재 color, font 로만 제한되어 있어서 다른 경우도 있지 않을까 해서 따로 분류하는걸 말씀드렸습니당

근데 저는 sx의 제한이 value가 아니라 key도 제한하는걸로 이해를 했어요. Text 컴포넌트니까 font 관련 속성으로만 key를 제한하는걸로. 그 외에 혹시나 Text 에 padding을 주고 싶거나 그러면 css로 넘겨주는게 맞지 않나 싶어요!

> switch 문 등으로 key 에 따라 원하는 value 를 얻는 helper 를 하나 만들 수도 있겠네요

그리고 이 말도 이해가 잘 안가는데 혹시 예시 들어주실 수 있을까요??

2022-10-25 09:42 UTC, healtheloper commented on src/components/common/Text/text.stories.tsx
> +      </Text>
아 네 저도 이제 Text.Highlight 가 있으니 inherit 가 필요한 상황이 더 없을 것 같아서 typography 에서 해당 코드를 지워도 되지 않을까 싶어 여쭤봤습니다~

2022-10-26 02:47 UTC, healtheloper commented on src/components/common/Text/index.tsx
> +  };
getCustomStyle 이라는 함수가 단순히 Text 뿐만 아니라 다른 컴포넌트에서도 쓰일 수 있다고 생각이 들었어요

그럼 sx 의 key 가 Text 와 관련된 color, font (fontWeight..., fontSize...) 만이 아닌 다른 key 를 가질 수도 있고, sx 의 key 값은 쓰는 곳에서 제한하여 보내면 된다고 생각이 들었어요

```tsx

 const getSXValue = (key, value) => {
   switch(key){
      case 'color':
        return theme.palette[value]
      case 'font관련':
        return fonts[key][value]
      default:
        return value
   }
 }

 const getCustomStyle = (sx) => (
    Object.entries(sx).reduce((acc, ([key, value])) => {
     acc[key] = getSXValue(key, value)
     return acc
    }, {});
  );

``` 

switch 에서 case 를 어떻게 분류할지, 추가적으로 어떤 case 가 더 들어오게 될 지 감은 잡히지 않긴합니다. 
sx 를 제한하는 다른 곳에서도 공통적으로 쓰일 여지는 있다고 생각하여 제안드린거니 참고만 해주세요~!

2022-10-26 07:41 UTC, jindonyy commented on src/components/common/Text/index.tsx
> +  };
제 생각에는 type에서 필요한 값만 받고있어서 저 switch문을 받을 필요는 없는거 같아요!
```ts
type TextSX = {
  fontSize?: keyof typeof fonts.fontSize;
  fontWeight?: keyof typeof fonts.fontWeight;
  fontFamily?: keyof typeof fonts.fontFamily;
  fontStyle?: keyof typeof fonts.fontStyle;
  color?: keyof IPalette;
  ...
}
```

2022-10-26 08:09 UTC, merged