[Park] Row Component refactoring
Co-Studo/Co-Studo-front pull request #60
Opened 2022-10-18 07:05 UTC by healtheloper

discussion #55 

reviewer 를 Jamie 만 할지, 다른분들도 할 지 고민스러운데 일단 모두 지정했습니다!
컴포넌트 담당자(?) 가 아닌 사람도 리뷰어로 추가하는게 좋을까요?

1. styled file 제거
- css prop 을 사용하자는 컨벤션에 의하여 styled 파일을 삭제했습니다.
  - 스타일을 고치기 위해 styled 파일로 들어가야하는게 조금은 불편하다는 생각을 했습니다

2. space-between

<img width="800" alt="스크린샷 2022-10-18 오후 3 53 36" src="https://user-images.githubusercontent.com/58503584/196357192-405d707f-3ee7-40fb-ac9a-2cbc11b52c83.png">

Jamie 가 discussion 에서 언급해주신 사항을 Jamie 는 flex-grow 를 통해서 해결하신 걸로 생각이 되었어요

처음엔 Column2Row 에 해당 속성을 사용하고자 했으나 Row 의 content 에서만 쓰이는 게 아니라
범용적으로 쓰이는 상황에서 원치않는 레이아웃이 생길 수 있어 content 로 사용되는 경우로만 적용하는 것으로 제한하였습니다.

```tsx
const Row = ({ content, left, right }: RowProps) => (
  <div
    css={{
      display: 'flex',
      gap: '0.5rem',
      width: '100%',
      alignItems: 'center',
      justifyContent: 'space-between',
    }}
  >
    {left}
    {content && <div css={{ display: 'flex', flexGrow: 1 }}>{content}</div>}
    {right}
  </div>
);
```

<img width="243" alt="스크린샷 2022-10-18 오후 3 50 25" src="https://user-images.githubusercontent.com/58503584/196356515-721ece82-8423-43d7-8ce2-797aae06aedb.png">

해당 컴포넌트는 left 를 `AvatarGroup`, right 를 `Column2Row` 로 사용하고 있는데요, 
`Column2Row` 에 flex grow 설정을 하면 위와 같이 레이아웃이 밀립니다

태그 중첩이 많아지는 듯한 단점이 있지만 각 요소의 역할로만 따지면 어쩔수 없다고 생각했습니다.
- Column2Row -> flex column
- Contents -> space-between 했을 때 왼쪽 정렬 되어야함

3. content

- 위의 이유로 flex grow 를 설정했는데, 추가로 display flex 도 설정하였습니다.
- 단순히 div 태그를 사용하여 display:flex 가 반복사용되는 것을 줄이기 위함인데, content 에 fragment 로 감싸 사용해야해서 오히려 복잡해 보이려나 싶긴 한데, discussion 에서 예시로 들었던 부분 위해 추가했습니다.

```tsx
// before
<div css={{display: 'flex'}}>
  <span>안녕<span>
  <span>하세요</span>
</div>

// after
<Row content={
  <>
    <span>안녕</span>
    <span>하세요</span>
  </>
} />
```

자유롭게 의견주세욥~~!

2022-10-18 07:56 UTC, mina-gwak commented
고생하셨습니다 파크!!
그리고 함께 진행하는 프로젝트니까 모두 리뷰어로 지정해서 의견을 들어봐도 좋을 것 같아요 👍
<br/>

> 처음엔 Column2Row 에 해당 속성을 사용하고자 했으나 Row 의 content 에서만 쓰이는 게 아니라
범용적으로 쓰이는 상황에서 원치않는 레이아웃이 생길 수 있어 content 로 사용되는 경우로만 적용하는 것으로 제한하였습니다.

지금 진행되는 방향을 보면 Row 컴포넌트가 전체적으로 레이아웃을 잡아주는 컴포넌트가 되어가고 있는 것 같은데요, 지금과 같은 방식으로 Row 컴포넌트가 구성된다고 하면 content에서 flex-grow를 사용하는 것도 원치 않는 레이아웃을 야기할 수 있을 것 같아요. 

<img width="272" alt="버튼 레이아웃" src="https://user-images.githubusercontent.com/62706988/196367186-83299e80-9ffe-4647-b277-7f91be7c39eb.png">

위와 같은 버튼 그룹도 Row 컴포넌트를 사용해 나타낼 수 있을 것 같은데요!

<img width="264" alt="스토리북 예시" src="https://user-images.githubusercontent.com/62706988/196367397-8080aa07-0866-4158-8583-67982f042a3a.png">

저런 버튼 그룹을 표현하기 위해 left, content, right로 지정해서 넣어줬을 때 한쪽으로 치우쳐서 나타나게 되어서 원하는 레이아웃을 잡지 못하는 경우가 생길 수 있을 것 같아요. 그래서 그냥 사용하는 쪽에서 스타일을 지정해서 넣어주는 게 좀 더 좋지 않을까 싶습니다. 근데 이렇게 되면 Column2Row가 필요없어질 것 같기도 하네요..??

<br/>

그리고 gap도 미리 지정해두는 게 아니라 커스텀이 가능해야하지 않을까 싶어요! 레이아웃마다 내부 요소들 사이의 간격이 달라질 수 있는 부분인데, 0.5rem으로 고정시켜두면 사용하는 쪽에서 추가적으로 스타일을 지정해주어야하니 불편할 수 있을 것 같다는생각이 들었습니당

2022-10-18 07:58 UTC, mina-gwak requested changes
앗 그냥 코멘트로 달아버려서 다시 리뷰로 달았습니당 🥲

고생하셨어요 파크!! 이야기해보고 싶은 부분이 있어서 request changes로 달겠습니다!
그리고 함께 진행하는 프로젝트니까 모두 리뷰어로 지정해서 의견을 들어봐도 좋을 것 같아요 👍
<br/>

> 처음엔 Column2Row 에 해당 속성을 사용하고자 했으나 Row 의 content 에서만 쓰이는 게 아니라
범용적으로 쓰이는 상황에서 원치않는 레이아웃이 생길 수 있어 content 로 사용되는 경우로만 적용하는 것으로 제한하였습니다.

지금 진행되는 방향을 보면 Row 컴포넌트가 전체적으로 레이아웃을 잡아주는 컴포넌트가 되어가고 있는 것 같은데요, 지금과 같은 방식으로 Row 컴포넌트가 구성된다고 하면 content에서 flex-grow를 사용하는 것도 원치 않는 레이아웃을 야기할 수 있을 것 같아요. 

<img width="272" alt="버튼 레이아웃" src="https://user-images.githubusercontent.com/62706988/196367186-83299e80-9ffe-4647-b277-7f91be7c39eb.png">

위와 같은 버튼 그룹도 Row 컴포넌트를 사용해 나타낼 수 있을 것 같은데요!

<img width="264" alt="스토리북 예시" src="https://user-images.githubusercontent.com/62706988/196367397-8080aa07-0866-4158-8583-67982f042a3a.png">

저런 버튼 그룹을 표현하기 위해 left, content, right로 지정해서 넣어줬을 때 한쪽으로 치우쳐서 나타나게 되어서 원하는 레이아웃을 잡지 못하는 경우가 생길 수 있을 것 같아요. 그래서 그냥 사용하는 쪽에서 스타일을 지정해서 넣어주는 게 좀 더 좋지 않을까 싶습니다. 근데 이렇게 되면 Column2Row가 필요없어질 것 같기도 하네요..??

<br/>

그리고 gap도 미리 지정해두는 게 아니라 커스텀이 가능해야하지 않을까 싶어요! 레이아웃마다 내부 요소들 사이의 간격이 달라질 수 있는 부분인데, 0.5rem으로 고정시켜두면 사용하는 쪽에서 추가적으로 스타일을 지정해주어야하니 불편할 수 있을 것 같다는생각이 들었습니당

2022-10-18 08:05 UTC, healtheloper commented
@mina-gwak 

### flex grow

만약 element 가 세 개 인 것을 flex 로 사용하고 싶다면 left, content, right 로 꼭 사용할 필요 없이 모두 content 에 넣고 space-between 을 사용하는 방식으로 변경할 수도 있긴 할 것 같아요.

이렇게 생각해보니 left, right 가 space-between 을 가지는게 맞을까? 라는 고민이 들긴 하네요. 
간단한 Icon 과 함께 사용되는 prop 이라고 생각하면 left, right 는 min-content 정도로만 가지고 나머지 영역을 content 가 가져가는게 맞는 것 같아요, 그렇게 되면 체크인 체크아웃 버튼을 left, right 에 넣으면 안될 것 같고..

### Column2Row

Column2Row 는 Row 처럼 2 개의 Row 를 가지는 Column 이라고 생각하면 Row 의 자식요소로 쓰이지 않을 때에도 사용될 수 있지 않을까요??
ex) 왕관아이콘 ..

### gap
> 0.5rem으로 고정시켜두면 사용하는 쪽에서 추가적으로 스타일을 지정해주어야하니 불편할 수 있을 것 같다는 생각이 들었습니당

👍

2022-10-18 08:28 UTC, mina-gwak commented
@healtheloper 

<br/>

> 만약 element 가 세 개 인 것을 flex 로 사용하고 싶다면 left, content, right 로 꼭 사용할 필요 없이 모두 content 에 넣고 space-between 을 사용하는 방식으로 변경할 수도 있긴 할 것 같아요.

이렇게 사용하는 것도 가능하긴 한데 left, content, right에 각각 넣어줌으로써 추가적으로 div를 생성해 flex를 해줄 필요 없이 레이아웃을 잡을 수 있게 되는데 꼭 content로 다 넣어줄 필요가 있을까 하는 생각이 들어요! 

left, right의 경우는 처음에 content 부분이 메인이고 left, right에는 부가적인 요소가 들어간다고 생각해서 content에 flex-grow를 사용하는 방식으로 작성했던 건데, Row가 범용적으로 쓰이게 된다면 left, right를 꼭 그런 용도로 제한할 필요가 있을까 싶네요..! 그대로 space-between을 사용해도 괜찮지 않을까요?

<br/>

> Column2Row 는 Row 처럼 2 개의 Row 를 가지는 Column 이라고 생각하면 Row 의 자식요소로 쓰이지 않을 때에도 사용될 수 있지 않을까요??

아하 이런 용도라면 그대로 놔둬도 될 것 같아요! 그런데 이런 식으로 가로 배치를 하는 Row, 세로 배치를 하는 Column2Row 두 개가 존재한다고 하면 Column2Row가 Row의 하위요소라기보다는 뭔가 Layout 하위의 Row, Column 이런 식으로 동등한 레벨에 있는 게 좀 더 자연스러울 것 같다는 생각이 드네요..!

2022-10-18 08:41 UTC, healtheloper commented
@mina-gwak 

> 그대로 space-between을 사용해도 괜찮지 않을까요?

3개라면 left, content, right 로 쓰면 되지만 4개 라면 left, right 에 2개씩 넣고 사용해야 하는지, 5개라면 2/1/2 로 사용 해야 하는데 해당 컴포넌트를 이렇게 사용하는게 맞을까? 란 고민으로 저렇게 제안드렸었는데 이 부분은 어떻게 생각하시나요?

space-between 그대로 두고 사용하는게 괜찮으면, flexGrow 를 사용할 것인지 말지를 옵션으로 줄 수도 있을 것 같고,
content 에 옵션으로 넘겨서 사용하게 하면 기본동작을 하나 빼는 격이 될 것 같네욥

Row 에 너무 많은 것(4개,, 5, 6..)을 담지 않는다면 그대로 써도 괜찮을 것 같긴합니다

> Column2Row가 Row의 하위요소라기보다는 뭔가 Layout 하위의 Row, Column 이런 식으로 동등한 레벨에 있는 게 좀 더 자연스러울 것 같다는 생각이 드네요..!

👍 
종속적인 느낌이 없어서 분리하는게 좋겠다고 생각합니다

2022-10-18 12:11 UTC, mina-gwak commented
@healtheloper 

<br/>

아 개수가 많아지는 경우를 생각 못했네요... 흠 저희 프로젝트에서 여러 개가 담기는 경우가 있을까요? 저는 디자인에서 딱히 생각나는 부분이 없긴 한데,,

<br/>

> content 에 옵션으로 넘겨서 사용하게 하면 기본동작을 하나 빼는 격이 될 것 같네욥

옵션으로 넘긴다는 게 어떤 옵션을 말씀하시는 걸까요..?! flex-grow?

2022-10-18 12:40 UTC, healtheloper commented
@mina-gwak 

> 옵션으로 넘긴다는 게 어떤 옵션을 말씀하시는 걸까요..?! flex-grow?

예시가 부족했네요 content 에 적용하고자 하는 justifyContent ? 를 얘기하는 것 이었습니다!!
```tsx
<Row content={
  <>
    <div>1</div>
    <div>2</div>
    <div>3</div>
  </>
} justifyContent='space-between' />
```

Row content 내부에 flex 가 적용되어 있는게 기본 동작이기 때문에 이런 방법뿐이 안떠오르는데.. 급 별로네요

아래 방법은 flex 를 적용하는게 content 에 기본 적용이 안돼서, Row content 로 쓰는 이유가 없는 듯 하구요
```tsx
<Row content={
  <div css={{ display:'flex', justifyContent='space-between' }}>
    <div>1</div>
    <div>2</div>
    <div>3</div>
  <div/>
} />
```

다시 전자로 넘어와서,, 갯수가 많아지는 경우 크게 세등분해서 묶어서 넣는 방식으로도 해결은 될 듯 싶긴 하네욥

2022-10-19 05:32 UTC, mina-gwak commented
@healtheloper 

흠,, 근데 생각할수록 Row가 점점 더 애매해지네요 ㅠㅠ 

left나 right로 들어가는 요소도 여러 개가 있을 수 있는 건데 걔네는 안에서 감싸주고 있는 게 없으니 사용하는 쪽에서 감싸서 들어가고, content는 있으니 fragment로 감싸서 넣어주면 통일성도 없는 것 같고,, left, content, right로 나눠주고 있는 것도 그냥 div에서 작성할 수 있는 걸 불필요하게 컴포넌트로 감싸는 게 아닐까 하는 생각도 드네요. 너무 범용적으로 가려다보니 그런 게 아닐까 싶은데,,

차라리 처음 의도처럼 특정한 레이아웃에서 쓸 수 있도록 제한을 하던지 아래처럼 자주 쓰이는 스타일을 정의해서 가져와서 사용하던지 하는 방안들이 있을 것 같은데 혹시 어떻게 생각하시나요..??

```tsx
const flexSpaceBetween = css`
  display: flex;
  justify-content: space-between;
`

<div css={flexSpaceBetween}>
  <div>left</div>
  <div css={flexSpaceBetween}>
    <div>1</div>
    <div>2</div>
    <div>3</div>
  </div>
  <div>center</div>
</div>
```

2022-10-19 11:34 UTC, healtheloper commented
음.. 제이미 말처럼 너무 범용적으로 생각하는게 아닌가 싶긴 하네요

> 특정한 레이아웃에서 쓸 수 있도록 제한

이 부분에 동의하고, 그럼 해당 Row 를 어디로 제한할 지 다시 고려해보는게 좋을 것 같다는 생각도 들었습니다! 
(예를들어 Dropdown 의 List Item 이라던지.. )

레이아웃을 잡기위한 용도로 사용할빠엔, 레이아웃을 위한 컴포넌트를 만들어버리는게 나을 것 같아요
해당 의견에 동의하시고, 다른분들도 동의하시면 PR 은 close 하겠습니다!

2022-10-21 02:49 UTC, closed without merging