[Dony] validation 함수
Co-Studo/Co-Studo-front pull request #63
Opened 2022-10-22 16:23 UTC by jindonyy

close #47 

초반에 얘기했던 pipe는 한 value를 여러 함수에 넘겨주는 식인데 저희는 여러 값을 사용해야하고, validate 하는 함수가 boolean을 return 하기 때문에 사용하지 못할거 같아요. 그래서 all 이라는 함수를 만들었습니다!

validate 함수에서 values를 객체로 받는 이유는 error 메세지에 어떤 값이 잘못됐는지 명시해줘야할거 같아서예요!
근데 정확히 어떻게 잘못됐는지 알려주고 싶어서 고민인데요. 떠오르는 방법 중에 선택부탁드려요!
1. funcs와 함께 함수별로 에러 메세지를 받는다.
   -> value를 객체로 사용하지 않아도 된다. 그러나 funcs가 커질 수 있다.
  ```ts
// validation.ts
type Funcs<V> = {
  func: (value: V) => boolean;
  message: string;
};
const validate = <V>(values: V[], funcs: Funcs<V>[]) => {
  values.forEach((value: V) => all<V>(...funcs)(value));
};

// functional.ts
const all = <V>(...funcs: ((value: V) => boolean)[]) =>
  (value: V) =>
    funcs.every(({func, message}) => {
      const result = func(value);
      if(!result) throw new Error(message);
      return result;
    });
  ```
2. validate 함수가 아니라 isInteger 처럼 validate를 체크하는 각각의 함수에서 false일 시 에러 메세지를 던진다.
  -> boolean 값만 받고 싶은 경우 사용하지 못한다. 이 경우도value를 객체로 받아야한다.
  ```ts
type Number = { [ key in string]: number };

const isInteger = (number: Number) => {
  const stringNumber = number.toString();
  const result = number === parseInt(stringNumber, 10);
  if(!result) throw new Error(`${key} is not Integer.`);
  return result;
};
  ```
3. 그냥 지금 정도의 에러 메세지도 괜찮다.
  -> 문제인 값만 알고 왜 문제인지는 모른다.

2022-10-24 10:21 UTC, healtheloper requested changes
잘봤습니다 도니~
pipe, all 이외에도 validate 관련 함수를 만들어주셨네요,

코드에 실제로 어떻게 쓰이는지 storybook 처럼 예시코드가 제한적이어서 예상하기가 조금 어려웠는데,
이런 로직이 있는 부분은 간단히 테스트코드를 작성해봐도 좋겠다는 생각이 들었습니다! (로직 테스트는 어렵지 않아요!!)

그리고 validate 에 들어가는 values 가 꼭 객체이어야할까? 에 대한 고민도 있었어요,
해당 부분은 코드리뷰에 남기겠습니다!

2022-10-24 10:21 UTC, healtheloper commented on src/utils/validation.ts
> +};
해당 validate 가 다양한 곳에서 쓰여질 수 있는지를 고민해봤어요

만약 id 가 validate 를 통과하지 못했다면? -> throw Error -> app 이 깨짐
만약 id, password 같이 통과하지 못할 여지가 있는 곳에서는 Custom 한 ErrorBoundary 로 대응은 가능할 수 있으나 Error Message 를 `Please check ${key}` 로 통일해서 써야해서, Custom ErrorBoundary 로 에러메세지를 세팅할 수 있을까? 란 생각을 했습니다.

아예 validate 하는 함수에서 error message 를 지정해주는 건 어떤가요?

```tsx

const isInteger = (number: number) => {
   const stringNumber = number.toString();
   const ok = number === parseInt(stringNumber, 10);
   if(!ok) throw Error(`${number}는 Integer 가 아닙니다`);
   return ok;
}

const validate = (value, ...funcs) => {
  try{
    const ok = all(...funcs)(value);
    return { ok }
  }catch(error){
    return {
      ok: false,
      message: error.message
    }
  }
}
```

2022-10-24 16:14 UTC, jindonyy commented on src/utils/validation.ts
> +};
> 아예 validate 하는 함수에서 error message 를 지정해주는 건 어떤가요?

제가 위에 2번에 썼놓긴했어요..! 
근데 적어주신 예시를 보니 isInteger에서 throw Error를 하고있는데 setError에서 또 에러 메세지를 넣어주는 이유는 뭔가요??

2022-10-25 05:01 UTC, hemudi approved these changes
validate 함수까지 만들어주실 줄 몰랐는데 넘넘 고생하셨어요!!!!
error 메세지는 저도 2번의 방식대로 해당 validate 함수 내에서 지정해주는게 좋을 것 같다는 생각이 드네요!!
실제로 한번 사용해보고 만약 추가적인 의견이 있으면 추후에 말씀드리겠습니다!
^_^)b 고생하셨어요!

2022-10-25 05:01 UTC, hemudi commented on src/utils/validation.ts
> +};
확실히 validate 함수 내에서는 throw error 보다는 try catch가 좋은 것 같네요! ^_^)b

2022-10-25 05:54 UTC, healtheloper commented on src/utils/validation.ts
> +};
화면에서 에러메세지를 보여줘야 하는데 그것을 저장하기 위한 상태입니다~

2022-10-25 08:09 UTC, jindonyy commented on src/utils/validation.ts
> +};
아하 테스트한 곳이 input이였져 참 하하 감사함당

2022-10-25 08:15 UTC, merged