[Hemdi] RadioGroup useForm 적용
Co-Studo/Co-Studo-front pull request #93
Opened 2022-11-16 18:00 UTC by hemudi

close #91

## ✨ 구현 내역
별도의 상태관리 로직을 가지고 있던 RadioGroup 컴포넌트가 Form 태그 하위에서 사용 될 때 RadioGroup의 값을 Form에서 일괄적으로 관리 할 수 있게 RadioGroup 내에 useForm을 적용하였습니다.

### 1. useFormContext & useForm
```tsx
export const useFormContext = () => {
  const context = useContext(FormContext);
 // if (!context) {
    // throw new Error(
    //   'useFormContext should be used within FormContext.Provider',
    // );
 // }
  return context;
};

const useForm = (name: string, initValue?: string): FormHookReturns => {
  const context = useFormContext();

  if (!context) return null;
  ...
}
```
- useForm을 Form 태그 하위가 아닌 곳에서도 사용할 수 있게 error를 throw 하지 않고 null 또는 context를 반환하도록 처리하였습니다.

### 2. RadioGroup.Option
```tsx
const Option = () => {
  const { selectedValue } = useRadioContext(); 
  const { value: formValue, subscribe, validationMode } = useForm(name, selectedValue) ?? {};

  const isChecked = (formValue ?? selectedValue) === value;
  const handleChange = onChange ?? subscribe(validates)[validationMode];

  return (
    <div>
      <input
        ...
        defaultChecked={isChecked}
        onChange={handleChange}
      />
      <label>{children}</label>
    </div>
  );
};
```
- selectedValue는 Form 하위에서 사용할 때는 초기값으로만 쓰이고 Form 에서 사용되지 않을 때는 [기존의 방식](https://github.com/Co-Studo/Co-Studo-front/blob/dev/src/components/common/RadioGroup/radioGroup.stories.tsx#L14)과 같이 **외부에서 주입되는 상태값**으로 쓰입니다.
- RadioGroup 에서는 onChange 이벤트 시 값을 컨트롤 하는게 정석이라고 생각해 이벤트를 onChange로 한정지었습니다. 

## 😭 고민 사항
### 코드의 가독성
```tsx
const {
  value: formValue,
  subscribe = () => {},
  validationMode = 'onChange',
} = useForm(name, selectedValue) ?? {};

const isChecked = (formValue ?? selectedValue) === value;
const handleChange = onChange ?? subscribe(validates)[validationMode];
```

useForm이 Form 태그의 하위가 아닐 시 null 을 반환하게 한 탓에
null 일 때의 타입 체크를 요리조리 피해서 코드를 짜다보니 위와 같은 코드가 만들어졌습니다....
짜고보니 이게 과연 가독성이 괜찮은 코드인지 고민이 됩니다...

```tsx
const formControl = useForm(name, selectedValue);
const isChecked = (formValue?.value ?? selectedValue) === value;
```

원래는 위 처럼 useForm을 formControl 이라는 변수로 받아서 옵셔널 체이닝으로 썼는데
무수한 물음표로 코드가 띠용?스러워지는 것 같아 물음표를 줄이다가 현재의 방식으로 수정하게 되었습니다...ㅠ

해당 부분의 가독성이 괜찮은지 아니면 개선이 필요할지 의견을 남겨주시면 감사하겠습니다!ㅠㅠ

2022-11-17 03:25 UTC, healtheloper approved these changes, later dismissed
RadioGroup 을 Form 안에서 사용할 때와 아닐 때의 처리를 위해서 조금은 복잡해져서 그로인해 고민이 생기신 것 같네요..!

Form 을 사용하지 않을 때에도 useForm 을 무조건 써야하나? 라는 생각이 들어서,
차라리 Form 의 Field 로 만드는 컴포넌트를 하나 만들어서 사용하는건 어떨까 싶기도 하네요.
실제로 구현해보고 분리해본건 아니라 이렇게 시도해보는건 어떨까? 싶은 아이디어라서, 이런 방법은 어떠신지 궁금하네요

변경사항은 위 고민사항으로 인한 수정이 대부분인 것 같아 코멘트로 대체하겠습니다!

```tsx
const Field = ({component}) => {
  const {} = useForm()
  return cloneElement(component, {...})
}

<Form.Field 
  component={
      <StyledRadio.Group name="check-out-setting" selectedValue="public">
         <StyledRadio.Option value="public">공개</StyledRadio.Option>
         <StyledRadio.Option value="private">비공개</StyledRadio.Option>
       </StyledRadio.Group>
  } />

// OR

const Field = ({children}) => {
  const {} = useForm()
  // children 이 RadioGroup 이면.. Option 까지 들어가서..
  // 이외는 나중에..
}

<Form.Field>
  <StyledRadio.Group name="check-out-setting" selectedValue="public">
    <StyledRadio.Option value="public">공개</StyledRadio.Option>
    <StyledRadio.Option value="private">비공개</StyledRadio.Option>
  </StyledRadio.Group>
</Form.Field>
```

2022-11-17 03:25 UTC, healtheloper commented on src/components/common/Form/Form.tsx
댓글용

2022-11-17 14:52 UTC, mina-gwak approved these changes, later dismissed
저도 파크가 말씀하신 것처럼 시도해보는 것도 좋을 것 같다는 생각입니다! 지금 방식도 나쁘지 않고 가독성 측면에서 걱정하시는 부분도 개인적으로는 크게 복잡하다는 생각이 들거나 하진 않았는데, RadioGroup을 폼 내부, 외부에서 모두 사용하도록 만들 거라면 RadioGroup 컴포넌트가 어차피 selectedValue, onChange 등을 외부에서 받고 있으니 래핑하는 컴포넌트를 만들어서 주입해주는 것도 좋겠다는 생각이 들었어요.
기존의 RadioGroup은 원래대로 유지하고, 컴포넌트를 하나 만들어서 거기서 useForm 훅의 반환값으로 value와 onChange를 넣어주면 되지 않을까 싶네요..!
```tsx
const FormRadioGroup = ({
  selectedValue = '',
  name,
  children,
  onChange,
  validates,
  ...restProps
}: RadioGroupProps) => {
  const {
    value: formValue,
    subscribe,
    validationMode = 'onChange',
  } = useForm(name, selectedValue);

  return (
    <RadioGroup
      selectedValue={formValue}
      name={name}
      onChange={subscribe(validates)[validationMode]}
      {...restProps}
    >
      {children}
    </RadioGroup>
  );
};
```

2022-11-17 14:52 UTC, mina-gwak commented on src/components/common/Form/useForm.tsx
> +  if (!context) return null;
현재 방식으로 간다면 여기서 null이 아니라 FormHookReturns 타입의 객체를 반환하도록 하면 사용하는 쪽에서 null 체크 없이 사용할 수 있을 것 같긴 한데 좋은 방식일지는 잘 모르겠네요 🤔 어차피 빈 객체를 반환할 거라면 명시적으로 null을 반환해서 사용할 때 값이 없을 수 있다는 걸 알려주는 게 나을 것 같기도 하고.. 여튼 이런 방법도 있을 수 있다는 생각이 들어서 코멘트 달아봅니다..!

```tsx
if (!context) return {} as FormHookReturns;
```

2022-11-17 15:15 UTC, jindonyy requested changes, later dismissed

2022-11-17 15:15 UTC, jindonyy commented on src/components/common/Form/useForm.tsx
>        const { value: targetValue } = event.target;
```ts
const targetValue = event.target.value;
```
이게 더 깔끔할 듯합니당

2022-11-17 15:22 UTC, jindonyy commented
form 하느라 수고가 많네여ㅜㅜ
질문하고 싶은건 왜 radio는 왜 form밖에서 쓰려고 하나요? Textfield는 form 안에서 쓰고 radio는 밖에서 쓸 경우도 있는게 이상? 하다고 느껴져요.
한 페이지에서 form은 두개여도 되니 form 관련 태그들을 쓸 때는 항상 form으로 감싸주고 submit 이벤트를 써야하지 않나 싶어요.
제가 전체 폴더 구조를 이제봤는데ㅠㅠ 이거 때문인지 text input은 form 안에 있고 radio는 form 밖에 있는게.. 어색하네요.
```tsx
const Form = Object.assign(FormRoot, {
  TextField,
  RadiGroup,
});
```
저는 RadioGroup도 Form 안에 들어오는게 맞지 않나 싶어요!

2022-11-18 03:03 UTC, hemudi commented on src/components/common/Form/Form.tsx
> 차라리 Form 의 Field 로 만드는 컴포넌트를 하나 만들어서 사용하는건 어떨까 싶기도 하네요.

와 짱입니다!
그렇지 않아도 아직 PR 못 올린 TextArea 컴포넌트에서 label과 helper text 의 중복이 신경쓰여서
Form 하위 컴포넌트면 label과 helper text를 랩핑해주는 컴포넌트를 구상해보고 있었거든요!
파크께서 주신 아이디어에 합쳐서 한번 시도 해보겠습니다!! ^_^)b

2022-11-18 03:09 UTC, hemudi commented on src/components/common/Form/useForm.tsx
> +  if (!context) return null;
와 이런 방법도 있군요!! 
그렇지 않아도 어차피 없는 값이니 명시적으로 null을 체크하는게 좋을거 같다 생각해서 null을 return한건데
TypeScript 에서 null은 골칫덩어리라 코드짜면서 너무 괴로웠거든요...ㅠㅠ
null 때문에 너무 고통스러우면 적용해봐도 괜찮은 코드같습니다 ^_ㅠ)b
배워갑니당!! ^///^)b 감사합니다!!!

2022-11-24 02:51 UTC, healtheloper approved these changes
👍

2022-11-24 02:53 UTC, mina-gwak approved these changes
👏

2022-11-24 02:57 UTC, merged